.github/workflows/contracts.yml

Depends on #1 
The following jobs are defined:
- contracts build and test,
- contracts linting for `.sol` code and `.js` tests,
- slither static analyzer for contracts.
This solution does not cache `node_modules` and it needs to be addressed separately. 
Apologies for force-pushes, this is still a working draft and I need to test things.

GitHub Actions CI jobs

---

solidity/contracts/TBTCToken.sol
solidity/contracts/token/ERC20WithPermit.sol
solidity/contracts/token/IERC20WithPermit.sol
solidity/contracts/token/TBTCToken.sol
solidity/test/helpers/contract-test-helpers.js
solidity/test/token/ERC20WithPermit.test.js

TBTC is now a burnable ERC20 token with EIP2612 permit functionality.
User can authorize a transfer of their token with a signature conforming
EIP712 standard instead of an on-chain transaction from their address.
Anyone can submit this signature on the user's behalf by calling the
permit function, as specified in EP2612, paying gas fees, and possibly
performing other actions in the same transaction.
By the time of implementing this contract, to my knowledge, there is no other
audited EIP2612 token implementation than Uniswap V2 on which this code is
based on. OpenZeppelin has quite recently added permit to their ERC20
but this code is in a draft state, was released in the most recent
v4.0.0, and to my understanding was not audited yet and may have
breaking changes in the future. On the …

Burnable TBTC ERC20 token with permit

---

solidity/contracts/test/TestERC20.sol
solidity/contracts/test/TestERC721.sol
solidity/contracts/token/MisfundRecovery.sol
solidity/contracts/token/TBTCToken.sol
solidity/test/token/MisfundRecovery.test.js

In case someone sends tokens to TBTC token contract address, these
tokens can be recovered by the governance. We observed such cases of
misfunds for tBTC v1 so to become more user-friendly, we are giving
rescue tools to tBTC v2 governance.
In practice, recovery functions will have to be proxied through the
vending machine because the vending machine will be the owner of TBTC
token contract.

Allow TBTC contract owner to recover misfunded ERC20/ERC721 tokens

---

solidity/contracts/test/ReceiveApprovalStub.sol
solidity/contracts/token/ERC20WithPermit.sol
solidity/contracts/token/TBTCToken.sol
solidity/test/TBTCToken.test.js
solidity/test/token/TBTCToken.test.js

Depends on #4 
`approveAndCall` is not a part of ERC20 - it was specified in [ERC827](https://github.com/ethereum/eips/issues/827) and
slightly diverged for some implementations. This one is identical to
`approveAndCall` behavior of [KEEP token](https://github.com/keep-network/keep-core/blob/v1.0.1/solidity/contracts/KeepToken.sol#L29).
`approveAndCall` executes `receiveApproval` function on the spender as
specified in `IReceiveApproval` interface. Approves spender to withdraw
from the caller multiple times, up to the value amount. If this function
is called again, it overwrites the current allowance with the provided
value. Reverts if the approval operation reverted or if `receiveApproval`
call on the spender reverted.

Added `approveAndCall` to TBTC token

---

solidity/contracts/test/ReceiveApprovalStub.sol
solidity/contracts/test/TestERC20.sol
solidity/contracts/test/TestERC721.sol
solidity/contracts/token/ERC20WithPermit.sol
solidity/contracts/token/IERC20WithPermit.sol
solidity/contracts/token/MisfundRecovery.sol
solidity/contracts/token/TBTCToken.sol
solidity/hardhat.config.js
solidity/package.json
solidity/yarn.lock

Depends on #5 
This change required updating Open Zeppelin library to version 4.x which
supports Solidity 0.8. I have also cleaned up all usages of `SafeMath` as
Solidity 0.8 checks the arithmetics.
The same Solidity version is currently used in coverage pools.

Standardize Solidity version to 0.8.4

---

yearn/contracts/ConvexStrategy.sol
yearn/test/system/constants.js
yearn/test/system/convex-strategy.test.js
yearn/test/system/curve-voter-proxy-strategy.test.js
yearn/test/system/fixtures.js
yearn/test/system/functions.js

Refs: #7
Depends on: #8 
**Introduction**
This pull request introduces another Yearn strategy named `ConvexStrategy`, meant to be used with the Yearn vault for tBTC v2. It follows all conventions introduced in the previous PR (#8) and is quite similar to the first `CurveVoterProxyStrategy` but uses [Convex Finance](https://www.convexfinance.com/) to generate yield.
**The `ConvexStrategy` strategy contract**
This strategy is used in the existing vault for tBTC v1 ([Curve tBTC pool yVault](https://yearn.watch/vault/0x23D3D0f1c697247d5e0a9efB37d8b0ED0C464f7f)). The current implementation for tBTC v2 is based on the following repositories, especially on the last one:
- [General Yearn strategy template](https://github.com/yearn/brownie-strategy-mix)
- [Convex implementation for tBTC v1 …

Yearn: Convex strategy

---

.github/workflows/contracts.yml
.github/workflows/yearn.yml
.pre-commit-config.yaml
.prettierignore
solidity/.prettierignore
solidity/package.json
yearn/.prettierignore
yearn/package.json

This PR enhances https://github.com/keep-network/tbtc-v2/pull/12 with additional updates to packages code formatting.
In `solidity` and `yearn` packages we add `format` script that will execute linting for both `js` and `sol` file types, but also will run `prettier` for all supported files (e.g. `json`).

Updated to global format configuration

---

solidity/contracts/bridge/VendingMachine.sol
solidity/contracts/test/ReceiveApprovalStub.sol
solidity/contracts/token/TBTC.sol
solidity/test/bridge/VendingMachine.test.js

For simplicity and... it just looks better. Same approach as for just [`T`](https://github.com/threshold-network/solidity-contracts/blob/005339e6afa0af117fe9cff97b48f170e188c24b/contracts/token/T.sol) instead of `TToken`.

Renamed TBTCToken contract to TBTC

---

solidity/deploy/02_deploy_vending_machine.ts
solidity/deploy/03_transfer_roles.ts
solidity/hardhat.config.ts
solidity/package.json
solidity/yarn.lock

This change adds appropriate roles transfers defined by the deployment scenario. It also sets the initial `unmintFee` value to zero. Follow-up to https://github.com/keep-network/tbtc-v2/pull/17

Transfer roles in tBTC v2 deployment script

---

solidity/package.json
solidity/yarn.lock

Updated the dependency after merging the change about replacing assembly
`chainid()` call with `block.chainid` in `ERC20WithPermit.sol`.
See https://github.com/thesis/solidity-contracts/pull/10

Updated @thesis/solidity-contracts dependency to the most recent version

---

solidity/deploy/02_deploy_vending_machine.ts

It is expected that VendingMachine becomes the owner of TBTC token to manage
minting of the token.
Refs https://github.com/keep-network/tbtc-v2/issues/26

Transfer TBTC token ownership to VendingMachine

---

solidity/hardhat.config.ts
solidity/package.json
solidity/yarn.lock

Use a plugin that verifies contracts on etherscan.
Sample usage:
```
ETHERSCAN_API_KEY=<API_KEY> npx hardhat verify --network ropsten 0x8b9a07ef443bc49b59f45e7dec905c4a2229aa7a
```

Verify contracts on Etherscan

---

solidity/.prettierignore
solidity/package.json
solidity/scripts/prepare-artifacts.sh

This PR implements what was previously described in https://github.com/keep-network/coverage-pools/issues/159.
The package will have the following structure:
```
artifacts/               # copy of deployments/<network>/
build/contracts/         # build artifacts
contracts/               # source code
export.json              # single-file deployment export
```
- `artifacts/` - is a directory containing deployed contracts artifacts for the network the package is being created. It is assumed that a package is published for each supported network separately as per the [RFC-18](https://github.com/keep-network/keep-core/blob/main/docs/rfc/rfc-18-release-management.adoc), so we don't need to create separate directories per network.
- `build/contracts/` - is a directory containing compiled …

Prepare NPM package structure for package publication

---

docs/rfc/rfc-2.adoc

Specify a group selection protocol using a sortition pool, with the submitter of the expensive sortition transaction being reimbursed, and the frequency of wallet creation being set by the market based on the gas costs of sortition and the available reimbursement amounts.
For distributed key generation, use the protocol from `tss-lib` with a number of attempts over 7 days to avoid expensive re-sortition even if some operators are inactive. Misbehaviour accusations are resolved by governance.

RFC 2: group selection and DKG

---

yearn/contracts/ConvexStrategy.sol
yearn/contracts/CurveVoterProxyStrategy.sol

Method `setKeepCRV` should validate their input parameter to be less or equal to the `DENOMINATOR` value.

Validate `_keepCRV` parameter

---

yearn/contracts/ConvexStrategy.sol
yearn/contracts/CurveVoterProxyStrategy.sol
yearn/contracts/SaddleStrategy.sol

Depends on: #48 
This changeset adds the minimum output amounts while performing DEX swaps or liquidity deposits. The minimum output amount is calculated with the governable slippage tolerance parameter.

Minimum output amounts for swaps and liquidity deposits

---

docs/rfc/rfc-1.adoc

This PR rewrites RFC1 from an account balances perspective. 
There's still an open FIXME touching on #37 of how we want to handle minting TBTC from unswept balances. I'm down to leave that a `?` until we get that issue resolved separately and then go back and edit.

Account Balances

---

.github/workflows/contracts.yml
.github/workflows/npm.yml
solidity/.hardhat/networks_TEMPLATE.ts
solidity/config_tenderly.sh
solidity/deploy/01_deploy_tbtc_v2_token.ts
solidity/deploy/02_deploy_vending_machine.ts
solidity/hardhat.config.ts
solidity/package.json
solidity/scripts/prepare-artifacts.sh
solidity/tenderly.yaml
solidity/yarn.lock

We're adding jobs which will deploy and publish `tbtc-v2` contracts.
Published artifacts will be used in the Continuous Integration proccess.
`NPM` workflow will build & publish contracts every time there is a
change in contracts or in the files describing package dependencies.
The `-dev` suffix will be used in the name of the published package.
`Solidity` workflow will deploy and publish contracts every time
worklfow is triggered by the `workflow_dispatch` event. Published
package name will point to name of the environment on which the
contracts were deployed.
TODO:
TODO **after** merging and publishing new NPM package:
Refs:
https://github.com/keep-network/ci/pull/16

Migrate contracts and publish package

---

.github/workflows/contracts.yml

If we're using `NODE_AUTH_TOKEN` env variable in the `Publish to npm`
step, we need to specify the `registry-url` property in the step setting
up the node.
Otherwise publication of the package fails with error like this:
```
'@keep-network/tbtc-v2@0.1.1-ropsten.0' is not in the npm registry
```
Workflow run showing successful publication:
https://github.com/keep-network/tbtc-v2/runs/3686753776?check_suite_focus=true

Specify registry during node setup

---

docs/rfc/rfc-1.adoc

This PR re-writes the heartbeat approach. Previously, there wasn't a great way for the signers to read bitcoin blocks and slashing was too harsh.
The new approach signs ethereum blocks, collects which operators aren't around if a heartbeat fails, and then submits that on chain. This opens us up to an attack where the wallet is controlled by the adversary and now they can kick honest operators out of the sortition pool for a few weeks, but honestly that's not the worst they can do 🤷 
open questions for a different PR:
* who submits the transaction to the chain? (an unlucky alive operator?)
* who submits the (very expensive) transaction to remove the inactive operators from the sortition pool? I think I heard something about a gas station idea

RFC 1: make the heartbeat approach more concrete

---

docs/rfc/rfc-1.adoc

This PR clarifies some sweeping logic around when a deposit is valid for sweeping in regards to when the deposit was made.
The idea is that if you have an old wallet that is close to being closed, and a user circumvents the dApp to make a deposit into that wallet (instead of the primary wallet for whatever reason), then the operators of that old wallet don't need to sweep that deposit.

RFC 1: Only Sweep Deposits to the Youngest Wallets

---

docs/rfc/rfc-1.adoc

This PR clarifies that sweeps must be performed one at a time and that a sweeping transaction can not be constructed until the previous sweep is complete.

RFC 1: Linear Sweeps

---

docs/rfc/rfc-1.adoc

This PR adds a blurb about approving the contract to mint tbtc with your swept balance as soon as you have one, that way you don't have to make multiple transactions or come back later once the sweep has actually happened.

RFC 1: Reveal and Approve TBTC Mint

---

solidity/contracts/bridge/Bridge.sol

Refs https://github.com/keep-network/tbtc-v2/issues/79
Bridge manages BTC deposit and redemption and is increasing and decreasing balances in the Bank as a result of BTC deposit and redemption operations.
Depositors send BTC funds to the most-recently-created-wallet of the bridge using pay-to-script-hash (P2SH) which contains hashed information about the depositor’s minting Ethereum address. Then, the depositor reveals their desired Ethereum minting address to the Ethereum chain. The Bridge listens for these sorts of messages and when it gets one, it checks the Bitcoin network to make sure the funds line up. If they do, the off-chain wallet may decide to pick this transaction for sweeping, and when the sweep operation is confirmed on the Bitcoin network, the wallet informs the Bridge …

Bridge.revealDeposit implementation

---

tbtc-ts/.eslintrc.js
tbtc-ts/package.json
tbtc-ts/src/bitcoin.ts
tbtc-ts/src/deposit.ts
tbtc-ts/src/index.ts
tbtc-ts/test/data/bitcoin.ts
tbtc-ts/test/deposit.test.ts
tbtc-ts/yarn.lock

Refs: https://github.com/keep-network/tbtc-v2/issues/79
This pull request introduces tooling meant to be used for assembling and broadcasting Bitcoin P2SH deposit transactions. Specifically, it extends the `TBTC` interface by adding the following methods:
- `makeDeposit`: Function which can be used to perform an end-to-end deposit flow. Takes deposit parameters, depositor private key, and Bitcoin client as arguments. It scans the depositor account for UTXOs, constructs the P2SH transaction according to given parameters, and broadcasts the transaction over the network. The main purpose of that function are future e2e tests of the whole system.
- `createDepositTransaction`: Function which assembles the P2SH transaction based on given deposit parameters, depositor private key, and UTXOs. It …

Assemble P2SH deposit transaction

---

.github/workflows/contracts.yml
.github/workflows/yearn.yml

We have CI workflows scattered across various repositories. We try to keep their implementation as similar as possible. In this PR and the ones listed below we introduce a couple of changes which unify used solutions and fix small mistakes, such as:
* making tagging of published packages consistent
* passing `NPM_TOKEN` secret as variable instead of passing it by writing to file
* handling caching of npm/yarn dependencies via `setup-node` action
* adding `workflow_dispatch` job trigger where it's missing
* using Node.js in version 14.x instead of 12.x where possible
Related PRs in other repositories:
* https://github.com/keep-network/keep-core/pull/2776
* https://github.com/keep-network/keep-ecdsa/pull/941
* https://github.com/keep-network/tbtc/pull/842
* …

Unify CI workflows

---

docs/rfc/rfc-1.adoc

This PR implements a simplified version of btc sweeping fees and deposit sweeping selection.
Previously, we were allowing users to specify a max btc fee, and then we were attempting to simulate how much a transaction *would* cost if we *were* to run it, and then that cost would decrease as we added users, but increase as we had to attempt retries if the initial amount wasn't high enough to bribe the miners to be included in a block. This put us in bin-packing hell.
Now, we say "by depositing, you agree to be swept at whatever fee we choose, and we will endeavor to pick a reasonable fee". Governance sets a max fee to mitigate attacks (if the operators collude with the miners), and the operators would need to be adversarial anyway to modify the client away from the default behavior of …

RFC 1: Simplify the BTC Sweeping Fee Mechanism

---

docs/rfc/rfc-1.adoc

This PR removes/simplifies a previous design - staggering, in favor of an active wallet/backup wallet design. The design concern was that adding multiple wallets creates UI confusion, and intentionally depositing to the backup wallet leads to a situation where a deposit might go through before a new wallet is about to go live (making the backup no longer the backup).
Now, there's just one active wallet, new deposits go to that wallet, and the backup wallet is expected to sweep deposits that were made during the transition.

RFC 1: Remove the whole staggering section

---

docs/rfc/rfc-1.adoc

This PR fixes a bug in the sample bitcoin script where the naming of the parameters was misleading.
The `DUP HASH160 <signingGroupPubkey> EQUAL` and `DUP HASH160 <refundPubkey> EQUALVERIFY` sections are modeled after the normal [P2PKH](https://learnmeabitcoin.com/technical/p2pkh) script, which goes `DUP HASH160 <hash160(public key)> EQUALVERIFY CHECKSIG`
When I named the parameters, it would have made **much** more sense to name those parameters `signingGroupPubkeyHash` and `refundPubkeyHash` respectively, since they are hashes rather than the raw data.

RFC 1: Fix Bitcoin Script Forgotten Hash

---

solidity/contracts/bridge/BitcoinTx.sol
solidity/contracts/bridge/Bridge.sol

Improved documentation by adding tables explaining raw Bitcoin transaction format, transaction inputs, and outputs. Referenced these types from `BitcoinTx.Info` struct documentation.
I decided to extract `BitcoinTx.Info` to a separate file because the tables - although helpful to understand the format - were polluting `Bridge` contract code too much.

Moar Bitcoin details: documentation improvements

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.test.ts

Closes: #95 
Depositors can route their revealed deposits only to trusted vaults and have
trusted vaults notified about new deposits as soon as these deposits get swept.
Vaults not trusted by the Bridge can still be used by Bank balance owners on
their own responsibility - anyone can approve their Bank balance to any
address.
Governance can mark the given vault address as trusted or no longer trusted.
Vaults are not trusted by default.
Trusted vault must meet the following criteria:
- `IVault.onBalanceIncreased` must have a known, low gas cost.
- `IVault.onBalanceIncreased` must never revert.
Without restricting reveal only to trusted vaults, malicious vaults not meeting
the criteria would be able to nuke sweep proof transactions executed by ECDSA
wallet with deposits routed to them. …

Deposits can be routed only to trusted vaults

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.test.ts
tbtc-ts/src/deposit.ts
tbtc-ts/test/deposit.test.ts

Refs: #79 
According to [BIP141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#p2wsh) all operations around the `P2WSH` script should use `SHA256`. In our context, that means we should use this hashing when building deposit transactions and during deposit reveal, specifically while performing expected script hash validation. Initially, we were using `HASH256` (double `SHA256`) by mistake and were producing `P2WSH` transactions which could not be unlocked by the sweeping wallet. This changeset fixes this mistake.

Use SHA256 when dealing with P2WSH script

---

solidity/contracts/bank/Bank.sol
solidity/contracts/bridge/Bridge.sol
solidity/contracts/vault/IVault.sol
solidity/contracts/vault/TBTCVault.sol
solidity/test/bank/Bank.test.ts
solidity/test/vault/TBTCVault.test.ts

Closes #99 
```
function approveBalanceAndCall(address vault, uint256 amount) external 
```
The function sets `amount` as the allowance of a smart contract `vault` over the caller's balance and calls the vault via `receiveBalanceApproval`. TBTC Vault implements this function by minting TBTC.
This way, the Bank balance owner can mint TBTC in one transaction instead of having to execute two separate transactions: `Bank.approve` and `TBTC.mint`.
I have also renamed `IVault.onBalanceIncreased` to `receiveBalanceIncrease`. Now the naming is aligned with `IVault.receiveBalanceApproval`.

Bank.approveBalanceAndCall

---

docs/rfc/rfc-1.adoc

This PR overhauls the design for how we determine and communicate the bitcoin mining fee.
Major changes:
* We use a 3-block target instead of 25-block. 
* We do it totally off-chain using operators in sortition-order with no punishments/incentives
I think I wrote 25-block originally because I had 25 from the automated liquidation recovery work, but 250 minutes for btc confirmation is *bad*. 3 might still be too long.

RFC 1: Max BTC Fee Revamped

---

solidity/test/helpers/contract-test-helpers.ts

The current import for `BigNumber` causes an error on a clean install. Changing it from `@ethersproject/units/node_modules/@ethersproject/bignumber` to just `@ethersproject/bignumber` fixes this.

Fix broken import in contract-test-helpers

---

tbtc-ts/src/deposit.ts
tbtc-ts/src/index.ts
tbtc-ts/src/sweep.ts
tbtc-ts/test/data/bitcoin.ts
tbtc-ts/test/data/deposit.ts
tbtc-ts/test/data/sweep.ts
tbtc-ts/test/deposit.test.ts
tbtc-ts/test/sweep.test.ts
tbtc-ts/test/utils/mock-bitcoin-client.ts

Refs: #79
This pull request introduces tooling meant to be used for assembling and broadcasting Bitcoin P2WPKH sweep transactions. Specifically, it extends the TBTC interface by adding the following methods:
* `sweepDeposits`: Function that can be used to perform the end-to-end sweep transaction. It combines the provided UTXOs (must be either P2SH or P2WSH, may optionally include UTXO from the previous sweep function), creates a transaction with one output with value equal to the sum of all UTXOs values minus fee. The recipient of the created output is the wallet itself. NOTE: The caller must ensure the provided UTXOs are correctly formed, the wallet can spend them and their total value is bigger than the provided fee. The main purpose of that function are future e2e tests of the whole …

Assemble sweep transaction btc

---

docs/rfc/rfc-1.adoc

The `dkg` parameter that describes the minimum number of active members for
the DKG can be hardcoded along with the group size and threshold.
Refs https://github.com/keep-network/keep-core/pull/2792#discussion_r796433986

Define `dkg` parameter as non-governable

---

docs/rfc/rfc-6.adoc

Note: we may decide to integrate it with RFC 1 or not. Making it a separate RFC for now.
The goal of this proposal is to reduce on-chain cost and complexity related to transaction submitter responsibilities, reduce the cost of operating a client, and provide tools to punish free-riders not operating their nodes properly.
The scheme assumes that the majority of the group is honest and is interested in helping DAO to eliminate free-riders from the network while getting nothing in return. The group will vote to mark someone as ineligible for rewards if they consistently do not participate in off-chain heartbeats or if they skip their responsibilities for submitting on-chain transactions. 
A real-world analogy would be team members discussing one of them is not contributing to the work at all …

RFC 6: Transaction incentives

---

solidity/package.json
solidity/yarn.lock

We update that dependency to employ recent gas optimizations made in the library.

Bump up `@keep-network/bitcoin-spv-sol` to `3.3.0-solc-0.8`

---

solidity/contracts/bridge/Bridge.sol
solidity/hardhat.config.ts

Use the optimiser in tests, and use low-level hash functions where applicable. Further gas savings could be achieved by replacing all instances of `keccak256(abi.encodePacked(x, y))` with assembly code utilising the scratchpad memory, but the savings are negligible. Depends on https://github.com/keep-network/bitcoin-spv/pull/6 exposing `hash160View`.

Sweep gas optimisation

---

docs/rfc/rfc-1.adoc

This PR rewrites the transaction incentives section to summarize and point to RFC 6 so that internal to RFC 1, the concepts can still be referenced but can be followed for more information.
Tagging @pdyraga and @michalinacienciala for review
marking as a draft until #115 gets merged

RFC 1: Align RFC 1 Transaction Incentives With RFC 6

---

docs/rfc/rfc-1.adoc

RFC 1 is updated with more details about the redemption mechanism. Specifically:
- redemption constraints related to EVM limitations,
- how the redemption proof should behave,
- what is happening in case of a timeout,
- what is happening in case of fraud,
- how to rebalance the Bridge after fraud.
This change is an outcome of a long discussion with @lukasz-zimnoch and @tomaszslabon regarding the problems that occurred when implementing Solidity code in #128. The code in #128 has been adjusted to follow the approach described here.

RFC 1: Spec out details of redemption

---

docs/rfc/rfc-1.adoc

Given that a Bitcoin transaction could be so large that proving it on Ethereum would be impossible, fraud proofs need to be processed with a challenge-response approach. 
When a wallet unlocks a UTXO it needs to calculate a sighash and provide a signature over that sighash, one for each unlocked UTXO. Fraud is reported for a UTXO by providing a sighash along with the wallet's signature over that sighash. From that moment, the wallet has a certain time to defend itself against the challenge and prove that the UTXO was spent in an honest way.
UTXO unlocked by the wallet is spent in a fraudulent way if:
- that unlocked UTXO is a revealed deposit that was not proved as swept and can not be proved as swept, or
- that unlocked UTXO was not and is not the main wallet's UTXO.
The wallet is …

RFC 1: Redesigning fraud proofs

---

docs/rfc/rfc-1.adoc

This PR disambiguates the link between missed heartbeats and failed redemptions. Now, failed redemptions simply lead to wallet closures with no reference to heartbeats, and they'll be added to the work in #127 
Tagging @michalinacienciala and @pdyraga for review

RFC 1: Missed Redemptions and Consecutive Failed Heartbeats

---

solidity/contracts/GovernanceUtils.sol
solidity/contracts/bank/Bank.sol
solidity/contracts/bridge/BitcoinTx.sol
solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/VendingMachine.sol
solidity/contracts/test/BankStub.sol
solidity/contracts/test/BridgeStub.sol
solidity/contracts/test/ReceiveApprovalStub.sol
solidity/contracts/test/TestERC20.sol
solidity/contracts/test/TestERC721.sol
solidity/contracts/test/TestRelay.sol
solidity/contracts/token/TBTC.sol
solidity/contracts/vault/IVault.sol
solidity/contracts/vault/TBTCVault.sol
solidity/hardhat.config.ts

We updated pragma to ^0.8.9 to align it with other projects, e.g.
`@keep-network/ecdsa`. If we don't do that there is a problem with
importing the ECDSA wallets contracts.

Update pragma to ^0.8.9

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.test.ts

Closes: #137 
This change introduces a deposit treasury fee which works in the same way as the existing redemption fee. This is achieved using the governable `depositTreasuryFeeDivisor` parameter that determines how much of the deposited amount should be taken as a treasury fee. Since that parameter is governable and may change over time, the actual fee value is computed and stored upon deposit reveal. During the sweep proof submission, the fee is cut from each depositor's balance and the total collected fee is used to increase the treasury balance accordingly. This changeset also involves some refactoring intended to reduce the number of declared variables in order to avoid `stack too deep` error fired by the Solidity compiler.

Deposit treasury fee

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.test.ts

Closes: #150 
Depends on: #162 
So far, the sweep transaction fee was distributed over all deposits but the potential remainder was lost due to Solidity rounding. This change mitigates that problem by isolating the indivisible remainder and pushing it towards the last swept deposit determined according to the order of the inputs.

Handle precision loss during sweep transaction fee distribution

---

solidity/contracts/bridge/BitcoinTx.sol
solidity/contracts/bridge/Bridge.sol
solidity/hardhat.config.ts
solidity/package.json
solidity/test/bridge/Bridge.test.ts
solidity/yarn.lock

Refs: #165 
Proof validation logic is the first candidate to be moved out of the `Bridge` contract in order to reduce its size. It can be placed in the `BitcoinTx` library which already contains Bitcoin-specific types so placing the logic operating on those types seems to be the right move. Since `BitcoinTx` becomes a linked lib due to that change, the gas cost of the main functions will change as well as the `Bridge` contract size:
| Parameter                    | Before     | After      |
|------------------------------|------------|------------|
| `revealDeposit` cost         | 87606 gas  | 87746 gas  |
| `submitSweepProof` cost      | 249183 gas | 254624 gas |
| `requestRedemption` cost     | 105723 gas | 105774 gas |
| `submitRedemptionProof` cost | 138182 gas | 143300 gas |
| …

Bridge refactoring - extract proof validation code to `BitcoinTx` library

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.test.ts

Closes: #154 
This change introduces `depositDustThreshold` that protects against too small deposits. This mechanism is the same as the one existing for redemption requests.

Deposit dust threshold

---

.github/workflows/contracts.yml

This version is more stable and should produce fewer failures upon CI jobs.

Bump Slither version to 0.8.2

---

.github/workflows/contracts.yml
.github/workflows/npm.yml
solidity/README.adoc

We're adding a step that configures git to use `https://` protocol
instead of `git://` when downloading files.
We need this step because the `@keep-network/tbtc` which we update in next
steps has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
downloads one of its sub-dependencies via unathenticated `git://`
protocol. That protocol is no longer supported. See
https://github.blog/2021-09-01-improving-git-protocol-security-github/.

Configure git to don't use unauthenticated protocol

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Wallets.sol
solidity/package.json
solidity/yarn.lock

Refs: #139 
This function allows notifying the `Wallets` library about a proven fraud committed by a wallet and cause appropriate side effects like slashing and wallet termination.

Notify `Wallets` library about a proven fraud

---

solidity/contracts/bridge/Wallets.sol

The ECDSA registry's `closeWallet` function expects a `bytes32` `ecdsaWalletID`, not the `bytes20` `walletPubKeyHash`. This change fixes that mistake.

Fix argument of `closeWallet` function call

---

docs/rfc/rfc-1.adoc

This PR fleshes out the mechanism for moving BTC between wallets, which happens after a failed heartbeat, or after a deposit puts the wallet under the dust threshold.
Out of Scope:
+ How exactly operators are punished in the case of a punishment
+ Edge cases for what happens if a wallet transfers to a wallet that was active when the transfer starts, but then immediately starts to close itself, beginning a race
Tagging @pdyraga and @michalinacienciala for review
depends on #125

RFC 1: Moving Funds Between Wallets

---

docs/rfc/rfc-1.adoc

This PR changes the wallet closure approach to iron out some wrinkles in the previous challenge process.
Previously, we were letting the wallet transfer the bitcoin to whichever wallets they pleased, and then relying on a challenge to show that the chosen wallets were the closest, live wallets at the time.
Since we don't (want to) keep track of wallet state history (only the current state of wallets), we have no way of telling if there *was* another closer live wallet back when the wallet decided to move the funds - we can only tell if there is *still* a live wallet. This means that the challenge becomes a race where the state of the wallet you're using to challenge with can change out from under you.
To solve this, we separate out the concern into "these are the wallets I want to …

RFC 1: `intention-to-move`

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Wallets.sol
solidity/contracts/test/BridgeStub.sol
solidity/hardhat.config.ts
solidity/test/bridge/Bridge.test.ts

This PR adds functionality of redemption timeout notification.
One function was added: `notifyRedemptionTimeout`.
The function checks whether the redemption request exists and has timed out.
Further steps depend on the state of the wallet:
* if the wallet is in `Live` state:
- the wallet's pending redemptions value is decreased by the amount requested in redemption request (minus treasury fee)
- the tokens taken by the bank during the redemption request are returned to the redeemer
- the redemption request is moved from pending redemptions to timeout redemptions
- the wallet's operators are slashed (`TODO`)
- the wallet is marked as either `MovingFunds` (if there is mainUTXO set for the wallet) or `Closed` (if there is no main UTXO set for the wallet)
- if the wallet was marked as active …

Redemption timeout

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.test.ts

This PR adds a check of the wallet state in `submitSweepProof` (only `Live` and `MovingFunds` wallets can accept the proof).

Check wallet state during submit sweep proof

---

solidity/contracts/bridge/Bridge.sol

~~Depends on #196~~
The part of the logic resolving the wallet, validating its state and
validating the main wallet UTXO has been moved to a separate function.
This is needed to avoid "stack too deep" problems when refactoring the
code moving sweeping functionality to a separate library, out of the
`Bridge` contract (will be done in the next PR).
Gas usage increased a little (~164 units worst case):
```
|  submitSweepProof       ·   181754  ·   336087  ·    255233  │
|  submitSweepProof       ·   181884  ·   336251  ·    255380  │
```
Also, made `Bridge` `immutable` fields mutable.
These fields will have to be extracted into `BridgeState` structure to fix the
problem with `Bridge` contract size (in the next PR) so we will no
longer be able to use the `immutable` keyword for them. Also, …

Refactor two: Extract logic resolving sweeping wallet to separate function, make Bridge fields mutable

---

typescript/src/deposit.ts
typescript/src/index.ts
typescript/src/sweep.ts
typescript/test/data/sweep.ts
typescript/test/deposit.test.ts
typescript/test/sweep.test.ts

Refs: #146 
That function was marked as deprecated as it does not fit the current design. This pull request removes it.

Get rid of `getActiveWalletPublicKey` function

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/IRelay.sol
solidity/contracts/bridge/Sweep.sol
solidity/contracts/test/BridgeStub.sol
solidity/hardhat.config.ts
solidity/test/bridge/Bridge.test.ts
solidity/test/bridge/bridge-fixture.ts

~~Depends on #198~~
A refactoring of the Bridge contract is required given the contract size
constraints. This change is another step on this journey. Sweep
functionality is extracted to a separate, externally linked library. No
changes to the logic in the sweeping code were applied.
There were to small changes to the code and docs in `BridgeState`
committed separately: 7b4fefd1b40f51e9f49152cbebb95242f37a8efd, 0cb7816ce2f1ff338f3fb72fdfd82920dfb7d9b6.
Bridge contract size comparison before and after:
```
|  Bridge               ·     24.852   │
|  Bridge               ·     20.689   │
```
Gas costs comparison before and after:
```
|  revealDeposit           ·    94028  ·    96659  ·    94690   │
|  revealDeposit           ·    96041  ·    98672  ·    96703   │
|  submitSweepProof …
```

Refactor three: Extract deposit sweeping into a separate library

---

solidity/contracts/bridge/Bridge.sol

~~Depends on #200~~
Extracted code processing single non-change redemption output to
a separate function and split the code processing all outputs into two
functions. This should help  with the clarity of the code but most
importantly, help with fixing "stack too deep" problems after extracting
redemption code to an external library, out of the `Bridge` contract.

Refactor four: extract parts of redemption transaction outputs processing code to separate functions

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/Redeem.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.test.ts
solidity/test/bridge/bridge-fixture.ts

~~Depends on #201~~
A refactoring of the Bridge contract is required given the contract size
constraints. This change is another step on this journey. Redemption
functionality is extracted to a separate, externally linked library. No
changes to the logic in the redemption code were applied.
Bridge contract size comparison before and after:
```
|  Bridge               ·     20.826   │
|  Bridge               ·     15.495   │
```
Gas costs comparison before and after:
```
| revealDeposit          ·   96041  ·   98672  ·   96703  │
| revealDeposit          ·   96005  ·   98636  ·   96667  │
| requestRedemption      ·  100601  ·  118446  ·  108329  │
| requestRedemption      ·  105448  ·  123275  ·  113159  │
| submitSweepProof       ·  196251  ·  350622  ·  269763  │
| submitSweepProof …
```

Refactor five: Extract Bridge redemption logic into a separate library

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.test.ts
solidity/test/bridge/bridge-fixture.ts

~~Depends on #202~~
A refactoring of the Bridge contract was required given the contract size
constraints. This change is another step on this journey. Moving funds between
wallets functionality is extracted to a separate, externally linked library. No
changes to the logic in the moving funds code were applied. At this point, we
are safe with not exceeding `Bridge` contract size with any more functionalities
we want to add, so it is more about the consistency of the code rather than
fighting for more space in the contract.
Bridge contract size comparison before and after:
```
|  Bridge               ·     15.495 |
|  Bridge               ·      9.849 │
```
Gas costs comparison before and after:
```
|  revealDeposit           ·    96005  ·    98636  ·    96667 │
|  revealDeposit …
```

Refactor six: Extract Bridge moving funds between wallets logic into a library

---

solidity/contracts/bridge/BitcoinTx.sol
solidity/test/bridge/Bridge.test.ts
solidity/test/bridge/bridge-fixture.ts

~~Depends on #203~~
After extracting pieces of `Bridge` contract into separate, externally
linked libraries, we have space to make `BitcoinTx` library code inlined
and reduce the gas cost of proofs by ~5200 units of gas.
The size of `MovingFunds`, `Redeem`, and `Sweep` libraries increased by 3KB.
The gas cost of `submitSweepProof`, `submitRedemptionProof`, and
`submitMovingFundsProof` decreased by ~5200 units of gas.
Gas consumption comparison before and after:
```
| submitSweepProof        ·  196167  ·  350538  ·  269679 │
| submitSweepProof        ·  190843  ·  345200  ·  264341 │
| submitRedemptionProof   ·  132038  ·  209681  ·  177521 │
| submitRedemptionProof   ·  126830  ·  204488  ·  172598 │
| submitMovingFundsProof  ·  138735  ·  158895  ·  151751 │
| submitMovingFundsProof  · …
```

Refactor seven: BitcoinTx is no longer an externally linked library

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/Fraud.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redeem.sol
solidity/contracts/bridge/Sweep.sol
solidity/contracts/bridge/Wallets.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.Wallets.test.ts
solidity/test/bridge/Bridge.test.ts
solidity/test/bridge/bridge-fixture.ts

Refs https://github.com/keep-network/tbtc-v2/issues/165
Moved `Wallets` library internal storage fields out to the `BridgeState`.
This change aligns `Wallets` library with other libraries used by the
`Bridge` that keeps all the state inside `BridgeState` library. No major
changes to the logic - the only ones are around `updateWalletParameters`:
emitting just one event and updating parameters in one shot.
Bridge contract size change (before/after):
```
|  Bridge   ·      8.666 | 
|  Bridge   ·      8.750 │
```
Gas consumption change (before/after):
```
|  __ecdsaWalletCreatedCallback          ·   80851  ·   80875  ·   80868  │
|  __ecdsaWalletCreatedCallback          ·   80771  ·   97881  ·   88108  │
|  __ecdsaWalletHeartbeatFailedCallback  ·   43093  ·   46803  ·   44948  │
| …
```

Refactor ten: move the state out of Wallets library

---

solidity/deploy/00_resolve_relay.ts
solidity/deploy/04_deploy_bank.ts
solidity/deploy/05_deploy_bridge.ts
solidity/deploy/06_bank_update_bridge.ts
solidity/deploy/07_transfer_ownership.ts
solidity/hardhat.config.ts

Here we implement hardhat deployment script for Bank and Bridge
contracts.
Bridge contract requires a reference to WalletRegistry, so we added an
external deploy scripts definition in hardhat config.

Implement deployment scripts for Bank and Bridge

---

solidity/contracts/bridge/Redemption.sol

This PR replaces the use of a counter with a flag when checking at least one redemption output is present when redemption proof is submitted.
It causes a slight drop in gas usage for `submitRedemptionProof`:
* with integer counter: 
```
|  Contract        ·  Method                                      ·  Min        ·  Max        ·  Avg         ·  # calls      ·  eur (avg)  │
|  BridgeStub      ·  submitRedemptionProof                       ·     126677  ·     204334  ·      172452  ·           19  ·          -  │
```
* with boolean flag:
```
|  Contract        ·  Method                                      ·  Min        ·  Max        ·  Avg         ·  # calls      ·  eur (avg)  │
|  BridgeStub      ·  submitRedemptionProof                       ·     126599  ·     203968  ·      172197  · …
```

Use flag instead of counter when checking redemptions present

---

solidity/hardhat.config.ts

After the recent refactoring, neither Bridge nor BridgeStub contract
size is a problem.
See https://github.com/keep-network/tbtc-v2/issues/165

Enabled contract sizing for all contracts again

---

solidity/contracts/bridge/Redemption.sol
solidity/contracts/bridge/Sweep.sol

We decided to remove the TODOs because only a selected set of maintainers will be reimbursed for calling this function, and those maintainers will be working on round-robin duty. There is a low risk that someone will try to frontrun the call. At the same time, doing this change would complicate the code so we think it is not worth it.

Remove unnecessary TODO

---

.github/workflows/contracts.yml
solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/Fraud.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/bridge/Wallets.sol

Slither 0.8.3 fixes issues with false validation failures from
crytic/slither#1067.
TODO:

Use the latest Slither 0.8.3 in CI

---

solidity/contracts/test/BridgeStub.sol

Refs https://github.com/keep-network/tbtc-v2/issues/152
Since the size of the `BridgeStub` is no longer a problem, there is no point
in having multiple `BridgeStub` contracts for different test groups.

Removed unnecessary TODO

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/test/bridge/Bridge.Frauds.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/fixtures/index.ts

This PR addresses [this review comment](https://github.com/keep-network/tbtc-v2/pull/236#discussion_r863557924).
Timeout-related parameters are moved to the end in functions that update and return parameters as well as events and declarations.

Change the order of parameters

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.MovingFunds.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/fixtures/index.ts

Refs: #243
Depends on: #261 
Here we introduce the `notifyMovedFundsSweepTimeout` function that is meant to be used to notify about a timed out moved funds sweep process. Just like in the moving funds process, the recipient wallet must sweep the obtained funds with their own main UTXO in a finite time window. In case this time is exceeded, a third party can notify about this fact thus cause the wallet termination and a severe slashing of wallet operators' stakes.

Moved funds sweep timeout

---

solidity/contracts/bridge/Fraud.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.Frauds.test.ts
solidity/test/bridge/Bridge.MovingFunds.test.ts
solidity/test/data/fraud.ts

Closes: #243 
Depends on: #262
Signatures that unlock main UTXOs being subject of processed moved funds sweep request can be challenged as frauds. Wallets must be able to defeat those challenges. This change adds a path to the `defeatFraudChallenge` function which makes such defeats possible.

Integrate moved funds sweeps with fraud mechanism

---

solidity/contracts/bridge/DepositSweep.sol
solidity/test/bridge/Bridge.test.ts
solidity/test/data/deposit-sweep.ts

Closes: https://github.com/keep-network/tbtc-v2/issues/246
Closes: https://github.com/keep-network/tbtc-v2/issues/248
This changeset addresses two TODOs related to deposit sweep proof logic improvements.
First, it hardens the validation of the single sweep output. So far, it was possible to use the P2SH output with a proper 20-byte wallet PKH. Now, the output is strictly validated and must always be P2(W)PKH.
Second, the main UTXO detection in the inputs processing loop was improved. So far, it was possible to forge the actual input considered as the main UTXO by using another outpoint of the same origin transaction. Now, the output index is checked as well so strict equality is preserved.

Improve deposit sweep proof logic resiliency

---

solidity/contracts/vault/DonationVault.sol
solidity/test/vault/DonationVault.test.ts

Closes: #237 
BTC donations are needed to re-balance the system in some rare cases when the BTC:tBTC peg can be breached. This change introduces a new `DonationVault` that is meant to handle BTC donations. That vault is plugged-in into the deposit flow. An external actor willing to make a BTC donation just makes a regular deposit targeting the `DonationVault`. Once that deposit is swept by the target wallet, the depositor's tBTC balance is not increased in the Bank, and the deposit is routed to the `DonationVault` which ignores it as well. In effect, deposited BTC remains swept by the wallet but no tBTC-related side effects take place.

Donation vault

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Fraud.sol
solidity/contracts/bridge/Heartbeat.sol
solidity/test/bank/Bank.test.ts
solidity/test/bridge/Bridge.Frauds.test.ts

~~Depends on #263. Keeping as a draft until #263 is not merged.~~
Refs https://github.com/keep-network/tbtc-v2/issues/254
Malicious wallet member can accuse wallet for a fraud using off-chain
heartbeat message signed by wallet members periodically.
`defeatFraudChallengeWithHearbeat` function allows wallet members to
defeat such challenge.
`defeatFraudChallengeWithHeartbeat` function added to `Fraud` library
allows to defeat a pending fraud challenge against a wallet by proving the
sighash and signature were produced for an off-chain wallet heartbeat message
following a strict format. In order to defeat the challenge the same
`walletPublicKey` and signature (represented by `r`, `s` and `v`) must be
provided as were used to calculate the sighash during heartbeat message
signing. The fraud …

Defeat against fraud challenge with a heartbeat sighash

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/DepositSweep.sol
solidity/test/bridge/Bridge.test.ts
solidity/test/data/deposit-sweep.ts

Closes: #123 
This change adds the ability to support vault routing during deposit sweep. The routing can be done if all swept deposits point to the same trusted vault indicated by the `vault` parameter of the `submitDepositSweepFunction`. In that case, the `Bank` just increases the vault's balance by the sum of all swept deposits and the vault takes the responsibility for individual depositors' balances. If the `vault` parameter is the zero address or points to a non-trusted vault, no routing occurs and the depositor's balances are updated in the `Bank` individually.
Gas costs of `submitDepositSweepProof` before:
```
····················|··············································|·············|·············|··············|···············|··············
|  BridgeStub       · …
```

Support vaults during deposit sweep

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/test/bridge/Bridge.MovingFunds.test.ts

Closes: #252 
This pull request introduces the `resetMovingFundsTimeout` function that allows resetting the moving funds timeout for a given wallet that has not yet submitted its commitment due to a lack of `Live` wallets in the system. This way, the moving funds wallet can avoid the punishment due to the system-caused timeout violation.

Reset moving funds timeout

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/Fraud.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redemption.sol

Refs: #152 
All `walletPubKeyHash` fields in events are indexed now. It is essential for the wallet to be able to easily manage its lifecycle and react to events it is interested in. 
Also, redeemer and depositor fields in `DepositRevealed` and `RedemptionRequested ` events are indexed now. This will let the depositor and redeemer easily find their revealed deposits and redemption requests in the system. Should be helpful, especially for the dApp.
This change does not increase gas consumption significantly. Before/after comparison for selected functions is available in commit messages.

Indexed fields of Bridge events

---

solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/Redemption.sol

Refs #152 
[Removed TODO about making BridgeState parameters governable](https://github.com/keep-network/tbtc-v2/commit/af2970c796950aaa2b7942cf655032e9c3926a19). All those parameters are already governable - we have an entire set of `update*` functions in `BridgeState`.
[Removed TODO about enforcing a specific locktime of revealed deposits](https://github.com/keep-network/tbtc-v2/commit/dad4f7049d053937a80de0d2b0ed8c29e99fd14a). Off-chain clients need to validate revealed deposits anyway. Validation of locktime can be just another off-chain step. This way, `revealDeposit` transaction can be cheaper.
[Removed TODO about validating the wallet used for redemption](https://github.com/keep-network/tbtc-v2/commit/05a3700b0b55a437718ce729fb9e0dd6dcc6d77c). The oldest wallet should be used for …

Removed three TODOs from Bridge contract

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Redemption.sol
solidity/package.json
solidity/yarn.lock

Closes #152 
Updated `@openzeppelin/contracts-upgradeable` to `^4.6.0` which is a non-rc
version. Aligned `@openzeppelin/contracts` dependency to use the same version
number.
`@keep-network/random-beacon` and `@keep-network/ecdsa` updated to the most
recent versions that rely on the same `@openzeppelin` dependencies.
I have also added links to GitHub issues addressing the last two remaining
TODOs in smart contracts.

Dependency updates!

---

typescript/src/chain.ts
typescript/src/deposit-sweep.ts
typescript/src/deposit.ts
typescript/src/index.ts
typescript/test/data/deposit-sweep.ts
typescript/test/deposit.test.ts
typescript/test/utils/mock-bridge.ts

Here we introduce the `Identifier` interface that is meant to represent a generic chain identifier. This way, we can decouple deposits from Ethereum addresses and their parsing and validation rules thus making the `typescript` library more friendly for potential multichain support.

Replace Ethereum addresses with chain identifiers

---

solidity/deploy/09_transfer_proxy_admin_ownership.ts
solidity/package.json
solidity/test/bank/Bank.test.ts
solidity/test/bridge/Bridge.Deployment.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/bridge/EcdsaLib.test.ts
solidity/test/bridge/Heartbeat.test.ts
solidity/test/bridge/VendingMachine.test.ts
solidity/test/fixtures/bridge.ts
solidity/test/fixtures/vendingMachine.ts
solidity/test/vault/DonationVault.test.ts
solidity/test/vault/TBTCVault.test.ts
solidity/yarn.lock

We noticed problems with hardhat-deploy-ethers breaking functionalities
of other plugins that don't use it, e.g. @openzeppelin/hardhat-upgrades.
We use plain @nomiclabs/hardhat-ethers instead.
Refs https://github.com/keep-network/tbtc-v2/issues/250
Refs https://github.com/keep-network/tbtc-v2/issues/267

Replace hardhat-deploy-ethers with @keep-network/hardhat-helpers

---

solidity/contracts/vault/TBTCVault.sol
solidity/test/vault/TBTCVault.test.ts

Depends on https://github.com/keep-network/tbtc-v2/pull/287
Refs https://github.com/keep-network/tbtc-v2/issues/256
Refs https://github.com/keep-network/tbtc-v2/issues/289
This change cleans up the nomenclature. `Bridge` has `deposit` and `redemption`
actions while `TBTCVault` has `mint` and `unmint` actions. This way, the act of
going from TBTC to `Bank` balance is `unminting`, and the act of going from
`Bank` balance to BTC is `redemption`.

TBTCVault is unminting TBTC to Balance instead of redeeming

---

solidity/contracts/vault/TBTCVault.sol
solidity/test/vault/TBTCVault.test.ts

~~Depends on #309. Keeping as a draft until #309 is not merged.~~
Refs: https://github.com/keep-network/tbtc-v2/issues/39
ERC20 and ERC721 can be sent mistakenly to `TBTCVault`, two functions allow the
governance to recover them. Most importantly though, the governance can use
`recoverERC20` to recover TBTCv1 tokens sent by `VendingMachine` to `TBTCVault`
after the upgrade.

Allow the governance to recover ERC20 and ERC721 from TBTCVault 

---

solidity/test/bridge/VendingMachine.Upgrade.test.ts
solidity/test/fixtures/bridge.ts
solidity/test/vault/TBTCVault.Redemption.test.ts

Depends on: #312. Keeping it as a draft until #312 is merged.
Refs: #39
Added test covering `VendingMachine` -> `TBTCVault` upgrade process.
**Step 1 - TBTC v1 transfer**
TBTC v1 is transferred from `VendingMachine` to `TBTCVault` along with
TBTC v2 token ownership.
**Step 2 - TBTC v1 withdrawal**
Governance withdraws TBTC v1 from `VendingMachine` *somewhere*.
Governance unmints TBTC v1 to BTC *somehow*.
**Step 3 - BTC donation**
Governance donates BTC to `TBTCVault`.
**Step 4 - functioning system**
The system works. Users can mint and unmint TBTC v2.

VendingMachine -> TBTCVault upgrade test

---

solidity/contracts/vault/TBTCVault.sol
solidity/test/vault/TBTCVault.test.ts

~~Depends on #313. Keeping as a draft until #313 is not merged.~~
Refs #39
It is not enough to transfer TBTC token ownership. The entire Bank balance needs
to be transferred as well. Without the balance transfer, the new vault would not
be able to perform BTC redemption in the Bridge.

Transfer the entire TBTCVault Bank balance to a new vault during the upgrade

---

solidity/contracts/bridge/Bridge.sol

Closes: #39 
`Bridge` is an upgradeable contract deployed behind a `TransparentUpgradeableProxy`.
Accepting redemption data as bytes provides great flexibility. The `Bridge` is
just like any other contract with a balance approved in the `Bank` and can be
upgraded to another version without being bound to a particular interface
forever. For example, what if 2 years from now, `Bridge` uses a single wallet
with all network operators as key share holders with a weekly key rotation?
This flexibility comes with the cost though - developers integrating their
vaults and dApps with `Bridge` using `approveBalanceAndCall` need to pay extra
attention to `redemptionData` and adjust the code in case the expected structure
of `redemptionData`  changes.

Note on upgradeability for `Bridge.receiveBalanceApproval`

---

solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/bridge/Wallets.sol
solidity/test/bridge/Bridge.MovingFunds.test.ts
solidity/test/bridge/Bridge.Redemption.test.ts
solidity/test/bridge/Bridge.Wallets.test.ts

Refs https://github.com/keep-network/tbtc-v2/issues/255
Some revert messages were starting with `ECDSA wallet...` some others with
`Wallet...` and some others with `The wallet...`. This change aligns them using
the shortest version (:bytecodesavingsallthethings:).

Align wallet state revert messages

---

typescript/src/chain.ts
typescript/src/index.ts
typescript/src/redemption.ts
typescript/test/redemption.test.ts
typescript/test/utils/mock-bridge.ts

Closes https://github.com/keep-network/tbtc-v2/issues/307.
Depends on https://github.com/keep-network/tbtc-v2/pull/291.
This PR adds typescript code for requesting redemptions.

Request redemption in typescript

---

typescript/package.json

The new name is `@keep-network/tbtc-v2.ts` in order to match the convention used in `solidity` package.

Rename `typescript` npm package

---

solidity/contracts/bridge/DepositSweep.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redemption.sol

Refs: #255 
Main UTXO validation was a part of `OutboundTx.processWalletOutboundTxInput`. This change removes the main UTXO validation from there. For `submitRedemptionProof`, the validation happens in the newly introduced `resolveRedeemingWallet`. For `submitMovingFundsProof`, the validation happens inside `submitMovingFundsProof`.
First, this change allows saving gas on `submitMovingFundsProof` and `submitRedemptionProof` given we do not fetch wallet pointer twice from the mapping. Before/after:
```
| Bridge · submitMovingFundsProof · 200904 · 356450 · 304175 │
| Bridge · submitRedemptionProof  · 130155 · 208356 · 176074 │
| Bridge · submitMovingFundsProof · 200900 · 356446 · 304171 │
| Bridge · submitRedemptionProof  · 130103 · 208304 · 176025 │
```
Second, it allows to align wallet …

Introduced resolveRedeemingWallet, removed main UTXO validation from OutboundTx

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/test/BridgeStub.sol
solidity/test/bridge/Bridge.MovingFunds.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/bridge/Bridge.Redemption.test.ts
solidity/test/fixtures/index.ts
solidity/test/integration/Slashing.test.ts

Closes #258 
Parameters are set to be more forgiving for the early days of the network. Timeouts are pretty long and slashing amounts are minimal.
During this work, I realized we should improve validation for deposit and redemption parameters. The deposit dust threshold must be greater than the per-deposit max allowed Bitcoin network fee. The redemption dust threshold must be greater than the per-redemption max allowed Bitcoin network fee. Added the validation in f9f75faeed956fbce381be8d11017a23097877c1.

Revisited initial Bridge parameters

---

typescript/src/ethereum.ts
typescript/test/data/redemption.ts
typescript/test/ethereum.test.ts
typescript/test/utils/mock-bridge.ts

Closes: #347 
There was a change that modified how the redemption key is build. Instead of
building it as `keccak256(walletPubKeyHash | redeemerOutputScript)` we now build
it as `keccak256(keccak256(redeemerOutputScript) | walletPubKeyHash)`. The
documentation in ts-lib was updated, but we did not update the values and
bulding redemptions key itself in tests.
I also tested the function using `walletPubKeyHash` and `redeemerOutputScript` 
used in 
https://github.com/keep-network/tbtc-v2/blob/de265cf8dd52411f853f01d18c520af473448efd/solidity/test/bridge/Bridge.Redemption.test.ts#L252-L255
and the generated key was correct.

🚧 😇 🔑  Update construction of a redemption key

---

docs/index.adoc

This PR adds the rest of the params from https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/bridge/Bridge.sol#L263-L292 to the documentation.
I used the bridge as the source of truth here. Notably out of scope and still important to do is checking to make sure that the values are what we want them to be - that'll be a follow-up. This just makes sure that the bridge and docs agree, and that the descriptions are accurate.
Tagging @pdyraga or @michalinacienciala for review

Line up the bridge params with the documentation

---

solidity/hardhat.config.ts
solidity/tasks/index.ts
solidity/tasks/test-utils.ts
solidity/test/integration/FullFlow.test.ts
solidity/test/integration/Slashing.test.ts
solidity/test/integration/WalletCreation.test.ts
solidity/test/integration/utils/ecdsa-wallet-registry.ts
solidity/test/integration/utils/fixture.ts
solidity/test/integration/utils/staking.ts
solidity/tsconfig.json

Refs: #143 
This pull request exposes some useful test utils (defined in `test/integration/utils`) as Hardhat tasks that can be used from the outside. Those utils will be essential for system test scenarios (developed as part of #339) that must use the local Hardhat network until the Ropsten deployment goes live. 
For now, two new commands are available:
- `npx hardhat test-utils:register-operators` that registers an arbitrary number of pre-defined signers as sortition pool operators. This is required to perform wallet creation.
- `npx hardhat test-utils:create-wallet` that creates a wallet with a given public key and registers it in the bridge. This is required to perform deposits and redemptions.
I recommend exploring the commit history to get the full picture of each change.

Expose test utils as Hardhat tasks

---

typescript/src/bitcoin.ts
typescript/src/deposit-sweep.ts
typescript/src/deposit.ts
typescript/src/electrum.ts
typescript/src/ethereum.ts
typescript/src/proof.ts
typescript/src/redemption.ts
typescript/src/tbtc.ts
typescript/test/data/deposit-sweep.ts
typescript/test/data/redemption.ts
typescript/test/deposit-sweep.test.ts
typescript/test/deposit.test.ts
typescript/test/ethereum.test.ts
typescript/test/redemption.test.ts
typescript/test/utils/mock-bitcoin-client.ts

Refs: #143 
This pull request introduces some tweaks to functions that work with Bitcoin transactions.
First, we extract a separate type that represents the Bitcoin transaction hash (`TransactionHash`). We also make it explicit that this type represents a transaction hash in the byte order used by the block explorers and wallet software. This way we capture those details in one place which was not possible if we would still use the ordinary `string` type.
Second, all `make*` functions return now the transaction hash and the UTXO relevant for further processing (deposit UTXO or new main UTXO). The same was done for the `create*Transaction` functions. This change should allow all clients to follow up on the transaction after using one of the library functions.

Tweaks around Bitcoin transaction processing code

---

system-tests/test/deposit-redemption.test.ts
system-tests/test/utils/bitcoin.ts
system-tests/test/utils/deposit.ts
system-tests/yarn.lock

Refs: #143 
This PR bumps up the `@keep-network/tbtc-v2.ts` dependency in the `system-tests` module in order to get the latest changes introduced as part of PR #364 and adjusts the system tests code to work with them.

Adjust system tests to the recent `typescript` library changes

---

.github/workflows/npm-typescript.yml

We want that the `@keep-network/tbtc-v2` dependency is updated to the latest version before we publish the new version of the `@keep-network/tbtc-v2.ts` package.
This is achieved in the `Resolve latest contracts` step by using the `yarn upgrade @keep-network/tbtc-v2` command that bumps up this dependency according to the range specified in the `package.json` file and saves back that change there. However, the updated version is non-strict. That causes some unexpected problems during `tbtc-v2` version resolution in packages that depend on `tbtc-v2.ts`.
In order to fix the aforementioned problem, we just upgrade `@keep-network/tbtc-v2` with the `--exact` flag that guarantees that the upgraded version saved in `package.json` is unambiguous.

Strict contract resolution during `typescript` package publication

---

system-tests/yarn.lock

This change should fix the wrong `@keep-network/tbtc-v2` version resolution that causes the following error:
```
Cannot find module '@keep-network/tbtc-v2/artifacts/Bridge.json'
```

Update system tests's `yarn.lock`

---

system-tests/test/deposit-redemption.test.ts

The `getRedemptionRequest` function throws in case the given redemption key refers to a missing request. We need to adjust the system test assertion accordingly.

Fix deposit and redemption system test scenario assertion

---

system-tests/test/deposit-redemption.test.ts

Deposit and redemption system tests scenario uses the `rejectedWith` assertion that is a part of the `chai-as-promised` plugin. In order to use that assertion, we need to inject that plugin using the `chai.use` instruction.

Inject missing `chai-as-promised` assertions

---

system-tests/test/deposit-redemption.test.ts

Adds a missing `chai` import in deposit and redemption system test scenario.

Add missing `chai` import

---

solidity/contracts/bridge/Bridge.sol
solidity/test/bridge/Bridge.Deposit.test.ts
solidity/test/bridge/Bridge.MovingFunds.test.ts
solidity/test/bridge/Bridge.Redemption.test.ts
solidity/test/fixtures/bridge.ts

The initialization function on the Bridge implementation contract was left
uninitialized. Anyone could call that method and set any parameters they wanted.
Because the Bridge contract is designed to be upgradeable, there was a risk that
future upgrades might introduce vulnerabilities (e.g. by adding
delegatecall/sefdestruct capabilities) that could be exploited by an
unauthorized account calling the initialize method on the implementation
contract. Adding `_disableInitializers` to `Bridge` contract constructor fixes
the problem.

Add `_disableInitializers` to `Bridge` contract constructor

---

solidity/package.json
solidity/yarn.lock

We update @keep-network/hardhat-helpers version to 0.6.0-pre.9 as it
contains improvements introduced in https://github.com/keep-network/hardhat-helpers/pull/27
that will modify the artifact exported for proxy contracts. The new
artifact matches the artifacts produced for contracts deployed non-proxy
way, which is important for Go code generator.

Update @keep-network/hardhat-helpers version

---

.github/workflows/npm-contracts.yml

We want to add `--exact` flag so the version of tagged package is
resolved to an exact value. Without this flag by default the version is
resolved by adding `^`, which can cause problems when resolving versions
with `-dev`, `-goerli`, `-mainnet` suffixes.

Use upgrade --exact for NPM package publication

---

solidity/package.json
solidity/yarn.lock

We need the latest version of hardhat helpers so the external deployment script `03_deploy_wallet_registry.js` can be executed. Without the upgrade it throws an error: 
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="call", transaction={"from":"0x407190f04d838Ec47dad4C0e0D2a9c49d7737479","to":"0x9E3991842f115f93D59cb92aE508242FE965A662","data":"0x204e1c7a0000000000000000000000009e500a116ea139c8e72af8f7953438ad0720cdcd","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
```

Upgrading hardhat-helpers to 0.6.0-pre.10

---

solidity/hardhat.config.ts

`development` env is used for local development on networks other than
Hardhat. Currently, it is Geth. Having development env in the `deployments`
field prevents from the proper deployment of `tbtc` contracts on Geth. The
transaction won't be completed and the contract won't be deployed on
Geth. Removing it, so we can properly deploy `tbtc` contracts.

Removing development env from `deployments` option

---

solidity/deploy/17_transfer_proxy_admin_ownership.ts
solidity/hardhat.config.ts
solidity/package.json

Refs https://github.com/keep-network/keep-core/issues/3040
In this PR we separate contracts deployment. Hardhat will deploy dependency contracts when running tests with a "USE_EXTERNAL_DEPLOY=true" flag. This is a "all-in-once" approach. 
When deploying contracts on the development env. ex. Geth, each project `beacon, ecdsa, and tbtc` handles its own contracts deployment. We need to provide a path in the "deployments" field where those contract artifacts are saved.

Split development external contracts deployment

---

solidity/hardhat.config.ts

For the development env. we are not going to use "all-in-one" approach for deploying contracts that is available for Hardhat. Each project is responsible for its own contracts. 
`solidity-contracts` is a dependency in tbtc, and we need to add this dependency to the "development" field to point to the linked and deployed artifacts.

Making solidity-contracts dependency for development env

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/maintainer/MaintainerProxy.sol
solidity/test/bridge/Bridge.Redemption.test.ts
solidity/test/maintainer/MaintainerProxy.test.ts

In `BridgeState` we used to say that:
> Timed out requests are stored in this mapping to avoid slashing the wallets multiple times for the same timeout.
This was not true, because when it comes to requesting redemption we say that:
> There is no need to check for existence in timedOutRedemptions since the  wallet's state is changed to other than Live after first time out is reported so making new requests is not possible.
And when the redemption timeout is reported we say that:
> It is worth noting that there is no need to check if timedOutRedemption mapping already contains the given redemption key. There is no possibility to re-use a key of a reported timed-out redemption because the wallet responsible for causing the timeout is moved to a state that prevents it to receive new …

Delete entry from `timedOutRedemptions` when it has been processed

---

solidity/package.json
solidity/yarn.lock

The latest version has improvements to deployments scripts.

Bump up version of @keep-network/hardhat-helpers

---

solidity/package.json
solidity/yarn.lock

The range that we had in `package.json` for `@keep-network/tbtc`
dependency was no longer containing the packages that we wanted. Since
we introduced `-goerli` suffixed packages, those packages were also
withing the range (and we want only `-dev` suffixed packages to be
within the range). Instead of using suffixes in the ranges we can also
use tags, which should be easier to maintain. So now we use
`development` tag, which should always point to the latest `tbtc`
package meant for development purposes.

Use `development` tag for `tbtc` dependency

---

solidity/contracts/bank/Bank.sol
solidity/test/bank/Bank.test.ts
solidity/test/vault/TBTCVault.test.ts

Does not allow updating an existing allowance to a value that is non-zero to
avoid someone using both the old and the new allowance by unfortunate
transaction ordering. To update an allowance to a non-zero value one should
update to zero first or use `increaseBalanceAllowance` or
`decreaseBalanceAllowance` for an atomic update. We have been warning about this
case in `approveBalance` documentation, but we were not enforcing this behavior.
Now we have a `require` making sure the rule is obeyed.

Does not allow updating an existing allowance to a non-zero value

---

solidity/contracts/bank/Bank.sol
solidity/test/bank/Bank.test.ts

~~Depends on #404~~
The Bank smart contract implements EIP-2612 but used mapping `nonce` (singular)
instead of `nonces`. This might create an issue when third-party libraries
(that support EIP-2612) try to interact with the Bank and assume that nonces are
tracked with `nonces` instead of `nonce`. Fixed it by renaming `nonce` mapping
to `nonces`.

EIP-2612 complicance fix: n/nonce/nonces

---

solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/Fraud.sol
solidity/contracts/bridge/MovingFunds.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/bridge/Wallets.sol

~~Depends on #405~~
The timestamp/locktime is represented using 32 bits for gas efficiency and to be consistent with Bitcoin.
This way, `OperatorRewards` structure in `Rewards` contract takes a single EVM word and the reward withdrawal consumes less gas. `DepositRequest` structure in `Deposit` library of the `Bridge` contract takes two EVM words and the operation revealing a deposit and the operation sweeping a deposit consume less gas. `Wallet` structure takes 4 EVM words and wallet lifecycle operations consume less gas.
`FraudChallenge`, `MovingFundsSweepRequest` ,`Redemtion` libraries of `Bridge` contract represent the timestamp as `uint32` for consistency with the rest of the code.
Note that Bitcoin represents the locktime using 32 bits as well: …

Warn about 32-bits timestamp representation limitation

---

solidity/contracts/vault/DonationVault.sol
solidity/contracts/vault/TBTCVault.sol

Depends on #407
The memory variables were not needed. The caller reference is more cost-effective than load.
This change brings some small savings to the gas used.
Before/After (Min/Max/Avg):
```
|  DonationVault  ·  donate   ·     -  ·      -  ·  55068  │
|  DonationVault  ·  donate   ·     -  ·      -  ·  55034  │
|  TBTCVault      ·  mint     · 64283  · 120443  ·  93832  │
|  TBTCVault      ·  mint     · 64246  · 120406  ·  93795  │
```

Use msg.sender directly to save on gas

---

docs/rfc/rfc-1.adoc
solidity/contracts/bridge/Deposit.sol

During the course of the audit, auditors stated that if an attacker can operate a dedicated hardware device at 100 mh/s, he can explore a 64-bit space in ~200,000 days and guess someone's blinding factor.
It is worth noting the `blindingFactor` (64 bits) is not the only parameter that changes for every deposit: `refundLocktime` (32 bits) changes as a timestamp for every deposit, and walletPubKeyHash (160 bits) rotates according to the rules of an active wallet rotation.
All the mentioned values are a part of DepositRevealInfo so the space to explore is not 64-bit but 64+32=96 bits assuming the active wallet is known. The active wallet is rotating so there is a limited time to explore a 96-bit space and there is absolutely no financial incentive for anyone to do that as they gain nothing …

Improve blinding factor explanation

---

.github/workflows/contracts.yml

The `ubuntu-latest` runner used by us to run GH Actions jobs is getting migrated
from Ubuntu `20.04` to `22.04`
(https://github.com/actions/runner-images/issues/6399). The `22.04` version does
not work with the config of the `actions/setup-python@v4` action which we use
in the jobs running slither. We were getting following failures in workflows:
```
Version 3.8.5 was not found in the local cache
Error: Version 3.8.5 with arch x64 not found
The list of all available versions can be found here:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Based on
https://github.com/actions/setup-python/issues/555#issuecomment-1337036543, we
should update Python version to `3.9.12` or higher. Or we could configure job to
run on the hardcoded Ubuntu 20.04 runner. …

Fix slither job by upgrading Python to 13.10.8

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/test/bridge/Bridge.Deposit.test.ts
solidity/test/bridge/Bridge.Governance.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/bridge/Bridge.Redemption.test.ts

During the work on the optimistic minting fee in #424, I realized the validation of the deposit and redemption treasury fee parameter in the Bridge does not allow setting the fee to zero, while the Bridge supports the zero-case for deposit and redemption.
We have a condition in `Deposit.sol` in the `revealDeposit` function allowing to properly handle the case when the Bridge's deposit treasury fee is zero:
```
deposit.treasuryFee = self.depositTreasuryFeeDivisor > 0
? fundingOutputAmount / self.depositTreasuryFeeDivisor
: 0;
```
Similarly, we have a condition in `Redemption.sol` in the `requestRedemption` function allowing to properly handle the case when the Bridge's redemption treasury fee is zero:
```
uint64 treasuryFee = self.redemptionTreasuryFeeDivisor > 0
? amount / …
```

Zero deposit and redemption fees

---

typescript/src/deposit.ts
typescript/test/deposit.test.ts

For the dashboard we want to be able to mock the deposit transaction with custom mocked bitcoin client. This is needed to be able ot test the dashboard without the need to connect to the real bitcoin client.
For that we wanted to use `assembleDepositScript` function but the problem was that it used `Deposit` object as a parameter, which had `walletPublicKey` and `refundPublicKey`. We then hash it into `walletPublicKeyHash` and `refundPublicKeyHash` inside that function, so we didn't use `refundPublicKey` and `walletPublicKey` there at all besides that. From the dashboard perspective we only have the `refundPublicKeyHash` and we can`t really convert it to a `refundPublicKey` since the convertion goes as below:
`private key -> public key -> compressed public key -> public key hash (PKH) <-> …

Use public key hashes in assembleDepositScript()

---

README.adoc
docs/README.adoc
solidity/README.adoc
system-tests/README.adoc
typescript/README.adoc
yearn/README.adoc

The `shields.io` have changed the syntax of the endpoints generating status badges, resulting in showing false failure status when old syntax was used. Updating the READMEs to use the new syntax.
Read more: badges/shields#8671.
Refs:
https://github.com/keep-network/keep-common/pull/112
https://github.com/keep-network/sortition-pools/pull/198
https://github.com/keep-network/keep-core/pull/3449
https://github.com/keep-network/coverage-pools/pull/221

Fix badges after change in shields.io syntax

---

solidity/contracts/bridge/DepositSweep.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/vault/TBTCOptimisticMinting.sol
solidity/contracts/vault/TBTCVault.sol
solidity/deploy/06_deploy_tbtc_vault.ts
solidity/test/bank/Bank.test.ts
solidity/test/data/deposit-sweep.ts
solidity/test/vault/TBTCVault.OptimisticMinting.test.ts
solidity/test/vault/TBTCVault.test.ts

There are two permissioned sets in the system: Minters and Guardians, both set up in 1-of-n mode. Minters observe the revealed deposits and request minting TBTC. Any single Minter can perform this action. There is a 3 hours delay between the time of the request from a Minter to the time TBTC is minted. During the time of the delay, any Guardian can cancel the minting.
For any revealed, unswept deposit, any Minter can request minting using `requestOptimisticMint(bytes32 fundingTxHash, uint32 fundingOutputIndex) external onlyMinter` on `TBTCVault`.
Any Guardian can cancel the minting by calling `function cancelOptimisticMint(bytes32 fundingTxHash, uint32 fundingOutputIndex) external onlyGuard`.
If none of the Guardians canceled minting, any Minter can finalize the request by calling …

Optimistic minting

---

solidity/package.json
solidity/yarn.lock

We can't use `@tenderly/hardhat-tenderly` in versions `1.4.x` and higher on Node.js `v14`, as those `1.4.x` versions introduce dependency to `tslog` package, which is incompatible with `v14` of Node.js (works on `v16` or higher). There are also some problems with deployment scripts (possibly fixable) on `@tenderly/hardhat-tenderly` in versions `1.2.x`, so we're limiting the allowed versions to `<1.2.0`.
Using `"@tenderly/hardhat-tenderly": "^1.0.12"` in `tbtc-v2` was causing problems with building/testing of the `@threshold-network/solidity-contracts`, where we upgrade the `tbtc-v2` dependency.

Change SemVer range for `@tenderly/hardhat-tenderly` dependency

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Deposit.sol
solidity/test/bridge/Bridge.Deposit.test.ts
solidity/test/bridge/VendingMachine.Upgrade.test.ts
solidity/test/data/deposit-sweep.ts
solidity/test/integration/FullFlow.test.ts
solidity/test/integration/Slashing.test.ts
solidity/test/integration/data/integration.ts
solidity/test/maintainer/MaintainerProxy.test.ts
solidity/test/vault/TBTCVault.OptimisticMinting.test.ts

Closes: #439 
Consider this scenario:
- Alice reveals her Bitcoin deposit and routes it to vault 0xABC
- Eve notices Alice's TX in the mempool and front-runs it with the same data but the vault 0xDEF
As a result, Alice's deposit lands in vault 0xDEF and not in vault 0xABC. Both 0xDEF and 0xABC have to be trusted vaults but it is still an issue given it is not what Alice was asking for.
Here we change the validation requirements of Bridge.revealDeposit function. From now on, this function must be called by the same Ethereum address as the one used in the P2(W)SH BTC deposit transaction as a depositor.

Allow only the depositor to reveal a deposit

---

typescript/src/bitcoin.ts
typescript/src/deposit-sweep.ts
typescript/src/deposit.ts
typescript/src/electrum.ts
typescript/src/ethereum.ts
typescript/src/hex.ts
typescript/src/redemption.ts
typescript/test/data/deposit-sweep.ts
typescript/test/data/deposit.ts
typescript/test/data/electrum.ts
typescript/test/data/proof.ts
typescript/test/data/redemption.ts
typescript/test/deposit-sweep.test.ts
typescript/test/deposit.test.ts
typescript/test/ethereum.test.ts
typescript/test/hex.test.ts
typescript/test/proof.test.ts
typescript/test/redemption.test.ts
typescript/test/utils/mock-bitcoin-client.ts
typescript/test/utils/mock-bridge.ts

Handling TransactionHash as a string causes a lot of confusion when integrating with the `tbtc-v2.ts` library. To be more explicit we introduce a class that expects a hexadecimal string (either prefixed or not). The class exposes functions to output the value as a prefixed or unprefixed string and gives a way to easily reverse the hex.

TransactionHash as Hex class

---

solidity/contracts/vault/TBTCOptimisticMinting.sol
solidity/test/vault/TBTCVault.OptimisticMinting.test.ts

The optimistic debt is explained in the documentation in the following way:
> The debt represents the total value of all depositor's deposits revealed to the Bridge that has not been yet swept and led to the optimistic minting of TBTC. (...)
This explanation is perfectly correct but it is not how the debt was calculated for a non-zero optimistic minting fee. Previously, the optimistic minting fee was deducted from the debt. This is not correct - the fee is also optimistically minted and goes to the treasury address. All TBTC that is optimistically minted: the part that goes to the depositor and the part that goes to the treasury should be added to the optimistic minting debt. When the deposit is swept, it is paying off both the depositor's part and the treasury's part.

Optimistic minting debt calculation fix

---

typescript/src/ethereum.ts

The class defines common contract initialization and function to query events.
The constructor expects Deployment artifact to be provided, we define an interface to specify the required properties. The Deployment interface is based on the Deployment artifact produced by the hardhat-deploy plugin we use in our deployment scripts.

TS: Introduce common EthereumContract class

---

solidity/deploy/11_deploy_bridge_governance.ts
solidity/hardhat.config.ts

Closes: #456 
Here we make some adjustments to increase the flexibility of testnet deployments. The main goal is to have a short test feedback cycle that will allow checking multiple scenarios using different combinations of the contract's governance parameters. In order to achieve that, we must be able to change governable parameters quickly. This change sets a 60-second governance delay for testnet and passes the governance over testnet contracts to an address controlled by the dev team.

Adjust deployment scripts for testnet

---

solidity/contracts/relay/LightRelay.sol
solidity/contracts/test/GoerliLightRelay.sol
solidity/deploy/01_deploy_light_relay.ts

Refs https://github.com/keep-network/keep-core/issues/3467.
This PR adds the `GoerliLightRelay` smart contract that is intended to be used on the goerli network.
The contract is derived from the real-world `LightRelay` and overrides functions for returning previous
and current difficulties - the functions always return `1`.
The relay deployment script was modified accordingly.

GoerliLightRelay contract

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeGovernance.sol
solidity/contracts/bridge/BridgeGovernanceParameters.sol
solidity/contracts/bridge/BridgeState.sol
solidity/test/bridge/Bridge.Governance.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts

Refs #455 
The treasury address was not governable before. Making it governable now via `BridgeGovernance` contract, with the same delay as other `Bridge` parameters.
The Treasury will be initially set to the Token Holder DAO. If it proves unwieldy to make use of the fees via DAO voting, the DAO may decide to transfer the Treasury address to the Council or one of the Guilds.

Treasury address made governable

---

solidity/contracts/test/SystemTestRelay.sol
solidity/deploy/01_deploy_light_relay.ts
solidity/hardhat.config.ts

The tBTC Go client can be built for four networks/environments:
- `make all environment=local`: Build with contract packages deployed locally.
- `make all environment=development`: Build with contract packages published to the NPM registry and tagged `@development`.
- `make all environment=goerli`:  Build with contract packages published to the NPM registry and tagged `@goerli`.
- `make all environment=mainnet`: Build with contract packages published to the NPM registry and tagged `@mainnet`.
No matter the environment, we have an assumption in the Go code: the Ethereum implementation for the relay chain expects the contract to expose some functions available on the `LightRelay` contract.
It means that for all published NPM packages, tagged with `@mainnet`, `@goerli`, or `@development`, we …

Deploy LightRelay for all networks but goerli and system_tests

---

solidity/contracts/bridge/BridgeGovernance.sol
solidity/contracts/bridge/BridgeGovernanceParameters.sol
solidity/test/bridge/Bridge.Governance.test.ts

We had a set of tests where the described behavior of the test didn't reflect the actual return message. The expected revert message should've been "Change not initiated".
The other change is simplifying calls for variables. We do not need to call internal getters to access variables from the `BridgeGovernanceParameters` lib.

Bridge governance tests fixes

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeState.sol
solidity/deploy/18_disable_moving_funds.ts
solidity/test/bridge/Bridge.Parameters.test.ts

For the initial release, we want to prevent wallets from entering into the `MOVING_FUNDS`, `CLOSING` and `CLOSED` states. Wallets must remain `LIVE` to be able to sweep funds when the time comes. So far, the `walletClosureMinBtcBalance` governable parameter was set to its minimal value of `1` satoshi. That value means a wallet can be directly moved to the `CLOSING` state if their balance in the `Bridge` is `0` satoshi and the wallet is no longer the latest one (i.e. active). This is a problem for optimistic minting because all wallets will have `0` satoshi in the `Bridge` until sweeping is implemented. Here we fix that by allowing to set `0` as a value of the `walletClosureMinBtcBalance` parameter and use that value as default in the deployment scripts.

Set wallet closure minimum BTC balance to zero

---

.github/workflows/contracts.yml

In one of the previous commits we've changed the name of the envirinment variable used to store the private keys of the accounts used in deploy on Goerli testnet. We need to update the workflow's config as well.

Rename the environment variable storing account keys

---

solidity/hardhat.config.ts

Currently in the CI we use `hardhat-deploy` to verify contracts on Goerli, for which we don't need to use tags. Tags are used for verification using `@nomiclabs/hardhat-etherscan` - we would need to adjust CI and hardhat config to support it.

Remove the `etherscan` tag for `goerli` environment

---

solidity/hardhat.config.ts

This PR sets all the named account addresses to `0` for Goerli deployment.

Set addresses for Goerli deployment to 0

---

solidity/package.json

We've published the 1.0.0 version (for mainnet), we need to update the version in `package.json` to a higher version.

Update version to `1.0.1-dev`

---

.github/workflows/npm-typescript.yml

In the `package.json` for `typescript` we have defined a postinstall script which runs `typechain` script. When we run `yarn upgrade...` in the CI workflow publishing NPM package, the specified in the command dependencies get updated, other get installed, but the postinstall scripts do not get executed. If we want to run the scripts we can either run `yarn install` before `yarn upgrade ...` or run `yarn run postinstall` after the `yarn upgrade ...` step. We've opted for the second option.
Without running the postinstall scripts, the workflow was failing with the following message duing `yarn build`:
```
$ tsc --project tsconfig.build.json
Error: src/ethereum.ts(23,47): error TS2307: Cannot find module
'../typechain/Bridge' or its corresponding type declarations.
Error: …
```

Yarn postinstall scripts after `yarn upgrade...`

---

.github/workflows/npm-typescript.yml
typescript/package.json

We use typechain script to generate TS bindings for contracts that we install as dependencies. With postinall script the bindings were generated always when we installed the dependencies. Unfortunatelly if this package was being used in another project as dependency this postinstall script was also executed, which doesn't make sense as we publish the generated bindings as part of the package.
With this change here we move the typechain bindings geneartion to the build script so they are generated when building the package before publication.

Exclude typechain script from postinstall

---

typescript/src/electrum.ts

We need to have a possibility to add `options` object to Electrum client and we couldn't do that through tbtc-v2.ts lib. This is why we introduce additional and optional property `options` in `Credentials` interface.

Add a possibility to pass options to the Electrum client

---

typescript/src/electrum.ts

We want to use that type in the dApp and to be able to do that we need this variable to be exported.
We also change the name of it from `Options` to `ClientOptions` as the `Options` seems to generic.

Export ClientOptions type

---

solidity/package.json

The latest NPM package published for mainnet is 1.0.1. Bumping up the version number for development.

Bumping up version to 1.0.2-dev

---

solidity/package.json

We've published the 1.0.2 version (for mainnet), we need to update the version in `package.json` to a higher version.

Update version to 1.0.3-dev

---

typescript/src/deposit-sweep.ts

Adding this argument will allow SPV maintainers to submit SPV proofs of sweeps that involves deposits targeting a specific vault.

Add optional `vault` parameter to `submitDepositSweepProof`

---

typescript/src/index.ts

If we export as types only we cannot use functions to initiaite objects, e.g. we cannot use `BitcoinTransactionHash.from(...)`

Remove type from main exports

---

typescript/src/ethereum.ts

The function returns the address of the contract instance.

Add getAddress function to EthereumContract

---

typescript/src/bitcoin.ts
typescript/src/electrum.ts
typescript/test/data/deposit-sweep.ts
typescript/test/data/electrum.ts
typescript/test/data/proof.ts
typescript/test/data/redemption.ts
typescript/test/electrum.test.ts

Closes: https://github.com/keep-network/tbtc-v2/issues/422
In this PR we update the implementation of TypeScript Electrum integration to support Esplora/Electrs servers.
As per https://github.com/Blockstream/electrs/pull/36 verbose transactions are not supported by Esplora/Electrs.
This affects our implementation of `getTransaction` and `getTransactionConfirmations` functions.
For a consistent code in the client without alternative paths for different Electrum servers implementations I decided to not use verbose transactions at all.
1. Get the raw transaction
2. Deserialize the raw transaction
3. Find transaction block height by finding it in a history of
transactions for the output script included in the transaction.
4. Get the latest block height
5. Calculate number of confirmations by …

TS: Support Blockstream's Esplora/Electrs servers for electrum protocol integration

---

typescript/test/electrum.test.ts

In this PR we update the list of servers to run the Electrum tests against. The servers were confirmed to work correctly by running the tests in a loop 100 times.

TS: Update Electrum test servers configuration

---

solidity/test/vault/TBTCVault.OptimisticMinting.test.ts

Follow-up to #491 
Here we introduce some improvements that should facilitate the understanding of the optimistic minting unit tests. The changes are scoped only to the explanatory comments and test names.

Optimistic minting tests improvements

---

typescript/src/bitcoin.ts
typescript/test/bitcoin.test.ts

Refs: https://github.com/threshold-network/token-dashboard/issues/393
The `decodeBitcoinAddress` documentation says that this function decodes P2PKH and P2WPKH addresses into a public key hash. However, this requirement is not enforced by the function code. Here we add a validation that makes the function throw if the passed address is not PKH-based. That means the function will throw an exception if the passed address is, for example, P2SH or P2WSH.

Make `decodeBitcoinAddress` throw on non-PKH addresses

---

typescript/package.json

We need to export the `src/` directory for `sourceMap` to work.
See: https://www.typescriptlang.org/tsconfig#sourceMap

Import include `src/` dir in package exports

---

typescript/scripts/README.adoc
typescript/scripts/refund.sh

- A user must provide electrum client credentials to connect with Bitcoin chain
- Adjusting README accordingly to the change above and mentioning that a transaction fee is deducted from the deposit

Making electrum credentials required

---

typescript/package.json

In 0e1f62414b5c804c690fd32d4270b8de8a5d4cb3 we added a requirement to rebuild on postinstall. In this commit we make it explicit that we need to rebuild bcrypto.
Also the rebuild works only on node 14, which is confusing (see: https://github.com/keep-network/tbtc-v2/issues/509) so we update engines to be explicit that node 14 is required.

Explicitly rebuild bcrypto and use node 14

---

SECURITY.adoc

Depends on https://github.com/threshold-network/solidity-contracts/pull/137
This version is the same as one published in `threshold-network/solidity-contracts `repository. It may need further updates when Immunefi Bug Bounty program is established. If you have any comments to the Threshold version of `SECURITY.txt` please comment at https://github.com/threshold-network/solidity-contracts/pull/137 and I'll backport changes here.

Updating SECURITY.adoc to the common Threshold version

---

.github/workflows/typescript.yml

We were incorrectly executing the action with `work-dir` set to `solidity`.

Fix wrong configuration of the `Bump up package version` CI step

---

typescript/src/backoff.ts
typescript/src/chain.ts
typescript/src/ethereum-helpers.ts
typescript/src/ethereum.ts
typescript/test/utils/mock-bridge.ts

We noticed that requests to ethereum endpoints are failing to due server errors. In this PR we wrap all ethereum requests with a backoff retrier.
The backoff retrier is an implementation used in `tbtc.js` library (https://github.com/keep-network/tbtc.js/blob/9838c06f21082cc050fab5f1304b95d6fa3db6a7/src/lib/backoff.js).
Closes: https://github.com/keep-network/tbtc-v2/issues/499

Retries for Ethereum requests

---

typescript/src/electrum.ts

The constructor expects `retryBackoffStep` parameter. We should also add it to the `fromUrl` static function.

Accept retryBackoffStep as electrum's fromUrl parameter

---

typescript/src/chain.ts
typescript/src/ethereum.ts
typescript/src/optimistic-minting.ts
typescript/src/wallet.ts
typescript/test/utils/mock-bridge.ts

Refs: https://github.com/keep-network/pm/issues/33
Here we expose some additional getters in the `typescript` library: `TBTCVault.getOptimisticMintingCancelledEvents` and `Bridge.getNewWalletRegisteredEvents`. The monitoring system is interested in these events but the library has not exposed them so far.

Expose additional event getters required by the monitoring system

---

typescript/src/chain.ts
typescript/src/ethereum.ts
typescript/src/optimistic-minting.ts

Refs: https://github.com/keep-network/optimistic-minting/issues/71
Here we expose a getter allowing to fetch past `OptimisticMintingFinalized` events.

Expose `OptimisticMintingFinalized` events getter

---

typescript/package.json
typescript/src/chain.ts
typescript/src/ethereum.ts
typescript/src/index.ts

Refs: https://github.com/keep-network/tbtc-v2/issues/552
Here we expose a way of getting the total supply of the TBTC v2 token for an arbitrary block, using the `tbtc-v2.ts` library. This ability will be leveraged by the monitoring system to raise alerts in case of significant supply changes.

Expose TBTC v2 token total supply getter

---

monitoring/docs/monitoring-and-telemetry.adoc
monitoring/src/minting-monitor.ts
monitoring/yarn.lock

Closes: https://github.com/keep-network/optimistic-minting/issues/71
Here we add four system events that can be produced by the minting monitor:
A **warning system event** indicating that an optimistic minting request was not issued by the designated minter and another minter did that job. This event is sent to Sentry hub and should get team’s attention. The default action is investigating the cause of the designated minter idleness as the designated minter may be unhealthy/malicious or there may be a bug in the minters bot code.
A **warning system event** indicating that an optimistic minting request was not finalized by the designated minter and another minter did that job. This event is sent to Sentry hub and should get team’s attention. The default action is investigating the cause of …

Monitor minters health

---

docs/rfc/rfc-7.adoc

Refs https://github.com/keep-network/keep-core/issues/3512
No changes to the mechanism. Updated some parameter values based on the current state of the code. Some changes to the client were applied when this PR was in progress.

RFC-7: Updates to the values of timeouts and benchmarks

---

cross-chain/arbitrum/hardhat.config.ts
cross-chain/arbitrum/package.json
cross-chain/arbitrum/yarn.lock

We want the artifacts to be exported to `artifacts/l1` and `artifacts/l2` directories. Here we implement automatic export on package publication, with a helper task defined in https://github.com/keep-network/hardhat-helpers/pull/40.
To prepare the artifacts export run a command for a given network, e.g.:
```
yarn run export-artifacts:goerli
```
or to export and publish:
```
npm run prepublishOnly --network=goerli
```
----
Depends on: https://github.com/keep-network/hardhat-helpers/pull/40

Arbitrum: Add artifacts export script

---

cross-chain/arbitrum/README.adoc
cross-chain/arbitrum/external/arbitrumGoerli/ArbitrumWormholeTBTC.json

- Removed unused env. vars from the README
- The previous wormhole token was a T token instead of TBTC token. The attestation was done one more time with the correct TBTC address on Goerli Ethereum and now the new address of wormholeTBTC token is put in `ArbitrumWormholeTBTC.json`. Creation of a wrapped token [tx](https://goerli.arbiscan.io/tx/0x71c341cd3f3fc8c6816bdca36fe4e0dee990e85ef375b99f046dddc25ff0c7d0), new address [0x97b5fe27a82b2b187d9a19c5782d9eb93b82dac3](https://goerli.arbiscan.io/address/0x97b5fe27a82b2b187d9a19c5782d9eb93b82dac3)

Arbitrum module small fixes

---

solidity/deploy/34_deploy_wallet_coordinator.ts
solidity/deploy/35_transfer_wallet_coordinator_ownership.ts

Refs: https://github.com/keep-network/keep-core/issues/3512
In #575, we introduced the `WalletCoordinator` contract. Here we add some Hardhat deployment scripts allowing us to deploy that contract.

Deployment scripts for `WalletCoordinator` contract

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

Refs: https://github.com/keep-network/keep-core/issues/3512
Here we add a return type for the `validateDepositSweepProposal` function. This is needed by the contract binding generator that doesn't handle non-returning view functions properly.

Return bool from `validateDepositSweepProposal` function

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

This changeset renames the role of *a proposal submitter* to *a coordinator*. Also, it removes the ACL rule allowing wallet members to submit sweep proposals.
We [want to add the functionality](https://github.com/keep-network/keep-core/pull/3521#discussion_r1173652203) of requesting heartbeats through the `WalletCoordinator` contract. Once we add heartbeat requests, *a proposal submitter* role will no longer sound good. For this reason, *a proposal submitter* role has been renamed to *a coordinator* role.
Having every wallet member be able to submit sweep proposals to the wallet [enables the risk](https://github.com/keep-network/tbtc-v2/pull/575#discussion_r1151564813) of griefing the coordination protocol. The address authorized to submit proposals can keep submitting proposals that …

Wallet coordination: rework the ACL to submit proposals

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts
solidity/test/fixtures/index.ts

~~Depends on #607~~
With the existing, pretty computationally-expensive tECDSA signing algorithm, [we would prefer](https://github.com/keep-network/keep-core/pull/3521#discussion_r1173652203) not to execute heartbeats at the same time as other wallet actions (sweeping, redemptions, moving funds). Moreover, we would prefer not to execute heartbeats from multiple wallets at the same time.
Such coordination is complicated off-chain for the same reason as the coordination of sweeps and redemptions. We could - as we do now - execute heartbeats at fixed hours but it does not help with coordination between heartbeats and sweeps. Also, it does not solve the problem of multiple heartbeats simultaneously.
For this reason, the heartbeat has been made a first-class wallet action coordinated in the …

Wallet coordination: Heartbeat action

---

cross-chain/optimism/hardhat.config.ts

The old Council address should not be used due to the problems in Safe UI when on Optimism network. The Council has reported that the old address is unusable because a different Gnosis Safe factory is required for Optimism. The Council is now using a new address [0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA](https://app.safe.global/settings/setup?safe=oeth:0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA).

Changing Council address on Optimism

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

We missed the coordinator's address in `HeartbeatRequestSubmittedEvent` emitted by the `WalletCoordinator` contract. Adding it now. It is important to be able to track easily which coordinator posted the given proposal in case it did not meet the expectations/needs.

Added coordinator's address to HeartbeatRequestSubmitted

---

.github/workflows/system-tests.yml

We're decreasing frequency of running the tests (we do not develop contracts as actively as we used to so running them every 24h is too aggressive, especially that the tests use testnet funds). From now on we will run tests weekly (every Sunday at 0:00). We can still trigger the tests manually if needed.

Run system tests weekly

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

Refs: https://github.com/keep-network/keep-core/issues/3512
Here we extend the deposit sweep proposal by adding an array containing the reveal blocks of each deposit. This information strongly facilitates the off-chain processing. Using those blocks, wallet operators can quickly fetch corresponding `Bridge.DepositRevealed` events carrying deposit data necessary to perform proposal validation. Worth noting, this field is not explicitly validated within the `validateDepositSweepProposal` function because if something is wrong here the off-chain wallet operators will fail anyway as they won't be able to gather deposit data necessary to perform the on-chain validation using the `validateDepositSweepProposal` function.

Pass deposits reveal blocks as part of the sweep proposal

---

monitoring/src/deposit-monitor.ts

We currently have discord alerts that look like this:
This is serviceable on a laptop where one can paste the fields into a block explorer, or copy the sats and divide by 1e8, but *very* annoying on a phone. In either case, I would prefer to have a block explorer link and the BTC amount in BTC rather than sats, for easy viewing.
This PR makes that change!
Tagging @nkuba and @lukasz-zimnoch for review.
Notably, I don't see how to test this and I'm not sure how to deploy it, but I checked around in the code and I don't see anything downstream that cares about the names of these fields, so I think we'd be fine.

Use Human Readable Outputs in Deposit Monitoring

---

solidity/package.json

v1.3.0 was already released so we need to start a new version development.

Begin solidity 1.4.0-dev version

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

Two gas offsets have been adjusted as a result of User Acceptance Tests execution on Goerli.
`heartbeatRequestGasOffset` has been updated from `5_000` to `10_000`. Looking at the heartbeat request TX
(https://goerli.etherscan.io/tx/0x0b76d88351a7e8d85fea53be4e17931d2a753ffddd90e73bcc734230c9ac84c8) the difference between ETH burned and reimbursed is 0.00000349514053395 eth which is 3495 Gwei. Assuming the gas price was ~1 Gwei, we should increase the offset by ~3500 Gwei so 8_500. We add an additional 1_500 as a safety margin.
For `depositSweepProposalSubmissionGasOffset`, the situation is more complex because the cost of the transaction depends on the number of inputs. We decided to optimize for 10 inputs. This transaction was expected with the offset set to `20_000` and 10 inputs: …

Adjust WalletCoordinator gas offsets

---

solidity/.openzeppelin/mainnet.json
solidity/deployments/mainnet/WalletCoordinator.json
solidity/export.json
solidity/package.json

Adding deployment artifacts for the newly deployed `solidity/v1.4.0` version with the `WalletCoordinator` contract. Bumping up the version to `v1.5.0-dev`.

V1.5.0 bump

---

solidity/yarn.lock
typescript/yarn.lock

We have published new `@keep-network/random-beacon`, `@keep-network/ecdsa` and `@keep-network/tbtc-v2` packages. Those packages no longer include the `prepare-dependencies.sh` script from `@threshold-network/solidity-contracts` which was causing random failures during `yarn install`. As in some CI jobs we install the dependencies based on the lockfile (with the `--frozen-lockfile` flag), we need to update dependencies in the lockfile so that the new, improved packages would be used.
Refs:
https://github.com/threshold-network/solidity-contracts/issues/142
https://github.com/threshold-network/token-dashboard/pull/533
https://github.com/keep-network/keep-core/pull/3618
https://github.com/keep-network/coverage-pools/pull/233

Update dependencies to `random-beacon`, `ecdsa` and `tbtc-v2`

---

typescript/yarn.lock

We have published new `@keep-network/ecdsa` and `@keep-network/tbtc-v2` packages. Those packages no longer include the `prepare-dependencies.sh` script from `@threshold-network/solidity-contracts` which was causing random failures during `yarn install`. As in some CI jobs we install the dependencies based on the lockfile (with the `--frozen-lockfile` flag), we need to update dependencies in the lockfile so that the new, improved packages would be used.
Ref:
https://github.com/threshold-network/solidity-contracts/issues/142
https://github.com/threshold-network/solidity-contracts/pull/143
https://github.com/keep-network/tbtc-v2/pull/631

Update dependencies to `keep-ecdsa` and `tbtc-v2` packages

---

solidity/contracts/bridge/WalletCoordinator.sol
solidity/test/bridge/WalletCoordinator.test.ts

Refs https://github.com/keep-network/keep-core/issues/3609
Here we add the on-chain coordination for redemptions. This changeset enhances the `WalletCoordinator` contract with three methods:
- `submitRedemptionProposal` that can be used to submit redemption proposals for wallets
- `submitRedemptionProposalWithReimbursement` which is the reimbursable version of `submitRedemptionProposal`
- `validateRedemptionProposal` which can be used by off-chain wallet operators to validate proposals using static calls
Moreover, during the work on `validateRedemptionProposal` we noticed the need to harden the validation rules of `validateDepositSweepProposal` function. We added a rule which enforces that each deposit in the proposal is used exactly once.

Redemptions prototype: On-chain coordination

---

monitoring/Dockerfile

This reverts commit 2c7c63e15e3b7af800710770a458f93ff67eb1cc.
See the following comment for a full description https://github.com/keep-network/tbtc-v2/pull/629#issuecomment-1584316498

Revert "Don't run postinstall script separately from yarn install"

---

typescript/src/ethereum.ts

To be able to use it outside of the `Bridge` contract handle.

Make `buildRedemptionKey` function static

---

.github/workflows/contracts-docs.yml
solidity/hardhat.config.ts

Having all the contracts documented in one common file turned out to be hard to render by the GitBook. We're switching to documenting each contract file in a separate Markdown file.
As the generated files will be much smaller now and GitBook has its own file `ON THIS PAGE` section, we don't need to generate Table of Contents. The one thing that we also change as part of this PR is `rsyncDelete` setting - we'll have it set to `true`, in order to delete documentation of contracts which get removed from the repo. As we're not working directly on a `main` branch, this isn't dangerous (we'll see all the deletions in the PR diff).
Refs:
https://github.com/threshold-network/solidity-contracts/pull/149
https://github.com/keep-network/keep-core/pull/3657 …

Split contracts API doc into multiple files

---

solidity/deploy/81_upgrade_wallet_coordinator_v2.ts

We add a script for WalletCoordinator contract upgrade.
The current WalletCoordinator contract deployed to mainnet is owned by Threshold Council, so it cannot be upgraded right away by the deployer.
The deployer will deploy a fresh WalletCoordinator contract implementation, then Threshold Council needs to execute transactions to upgrade the WalletCoordinator proxy to the new implementation and set the initial values for newly added parameters.
Refs: https://github.com/keep-network/tbtc-v2/issues/641

Deployment script for WalletCoordinator upgrade

---

solidity/package.json

`solidity/v1.5.0` was already published, so we need to start a new version development.

Start solidity/v1.6.0-dev version

---

typescript/src/bitcoin.ts
typescript/src/chain.ts
typescript/src/ethereum.ts
typescript/src/redemption.ts
typescript/test/bitcoin.test.ts
typescript/test/ethereum.test.ts
typescript/test/redemption.test.ts
typescript/test/utils/mock-bridge.ts
typescript/test/utils/mock-tbtc-token.ts

This PR refactors the `requestRedemption` function to request redemption in one transaction(instead of 2: approve + requestRedemption) using the [`approveAndCall` ](https://github.com/thesis/solidity-contracts/blob/main/contracts/token/ERC20WithPermit.sol#L207) function from tBTC token contract. Then the tBTC token contract calls the [`receiveApproval`](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/vault/TBTCVault.sol#L193) function from the `TBTCVault` contract which [burns tBTC tokens and requests redemption](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/vault/TBTCVault.sol#L338).

Request redemption in one transaction

---

typescript/src/bitcoin.ts
typescript/src/electrum.ts
typescript/src/redemption.ts
typescript/src/wallet.ts
typescript/test/data/redemption.ts
typescript/test/electrum.test.ts
typescript/test/redemption.test.ts
typescript/test/utils/mock-bitcoin-client.ts
typescript/test/wallet.test.ts

Refs: https://github.com/threshold-network/token-dashboard/issues/553
Here we improve the logic of `findWalletForRedemption` function to handle the corner case when a wallet's main UTXO known to the `Bridge` was actually spent on Bitcoin but that change was not yet reflected to the `Bridge`. So far, `findWalletForRedemption` relied on `findAllUnspentTransactionOutputs` which does not return spent UTXOs so determining the actual main UTXO was not possible in the aforementioned corner case. Now, the `findWalletForRedemption` looks for recent wallet transaction history on Bitcoin and tries to match the actual main UTXO based on that. This change will allow submitting new redemption requests without downtime, even if the target wallet is performing an action at the moment.

Improve find wallet for redemption logic

---

typescript/src/redemption.ts
typescript/test/redemption.test.ts

Throw error when currently, there are no live wallets in the network and when the user requested redemption for all live wallets in the network using the same Bitcoin address - in that case, a user should use another Bitcoin address.

Improve errors in `findWalletForRedemption` function

---

.github/workflows/cross-chain-arbitrum.yml
.github/workflows/cross-chain-optimism.yml
.github/workflows/cross-chain-polygon.yml

We want the workflows building the cross chain projects to execute when changes are commited to the feature branches of PRs modifying files of those projects. We had all the config required to do that, except the most important part - the `pull_request` trigger, which we somehow missed.

Add `pull_request` CI trigger

---

typescript/package.json

We released version 1.3.0, so need to start the next one for development.

TypeScript: Start version 1.4.0-dev

---

cross-chain/base/deploy_l2/12_update_self_in_wormhole_gateway_mapping.ts

The link has changed for the docs, now it is https://docs.wormhole.com/wormhole/blockchain-environments/evm#base

Update Wormhole docs link for Base

---

system-tests/test/minting-unminting.test.ts

It happens that a reveal process starts when a deposit is not captured by the Bitcoin chain because it's out of sync. A delay is added to wait a bit for a chain to sync. This should fix:
```
1) System Test - Minting and unminting
when minting is initiated by making and revealing a deposit to the TBTCVault
"before all" hook: make and reveal deposit for "should broadcast the deposit transaction on the Bitcoin network":
Error: Electrum action failure: [daemon error: DaemonError({'code': -5, 'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.'})]
at Client.withElectrum (node_modules/@keep-network/tbtc-v2.ts/src/electrum.ts:190:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async …
```

Delaying reveal process in the "make and reveal a deposit" test.

---

typescript/package.json
typescript/src/bitcoin.ts
typescript/src/electrum.ts
typescript/test/bitcoin.test.ts
typescript/test/electrum.test.ts
typescript/typings.d.ts
typescript/yarn.lock

Refs: https://github.com/keep-network/tbtc-v2/issues/695
We use `bcrypto` to compute hashes, but since this library is a bit problematic, here we replace it with hashing algorithms from the `ethers` library. `ethers` has no `hash160` algorithm but under the hood `HASH160 = RIPEMD160(SHA256(X))` so it's possible to compute `hash160` using `ethers`.

Get rid of `bcrypto` dependency

---

typescript/package.json
typescript/yarn.lock

Refs: https://github.com/keep-network/tbtc-v2/issues/695.
In this PR `bitcoinjs-lib`library was added to `tbtc-v2.ts`.
Since there is a node version conflict between the newest `bitcoinjs-lib` (requires `node 16` or later) and `tbt-v2.ts` (requires `node 14`), an older version of `bitcoinjs-lib` was added(`6.0.2`).
Once we get rid of `bcoin` we can update `bitcoinjs-lib` to its newest version as it should be possible to use node 16 with `tbtc-v2.ts`.
I verified that the library was successfully installed.

Add `bitcoinjs-lib` dependency

---

typescript/package.json

We released version 1.4.0, so need to start a next one for development.

TypeScript: Start version 2.0.0-dev

---

typescript/package.json

We released version 2.0.0, so need to start a next one for development.

TypeScript: Start version 2.1.0-dev

---

typescript/src/lib/electrum/client.ts
typescript/src/lib/ethereum/index.ts
typescript/tsconfig.json

While integrating `threshold-dashboard` with the latest iteration of the SDK, some bugs have been spotted. This pull request presents spotted issues, proposes and explains solutions. Each solution is explained in an additional commit message.

Dashboard integration bugs

---

typescript/package.json

We released version 2.1.0, so need to start a next one for development.

TypeScript: Start version 2.2.0-dev

---

.github/workflows/contracts-docs.yml

As auto-generated contract API reference has been moved under https://docs.threshold.network/app-development/tbtc-v2/tbtc-contracts-api, we need to update the CI job that publishes those docs to take the new destination into account

Update auto-generated contract docs destination

---

typescript/package.json
typescript/src/lib/bitcoin/ecdsa-key.ts
typescript/yarn.lock

The currently used implementation of _Secp256k1_ curve turned out to be faulty in Browser environments since it uses Node specific APIs under the hood.
The solution was to replace the `tiny-secp256k1` library with `@bitcoinerlab/secp256k1` which is universal in use (both Node and Browser compliant).
<details><summary>
🛠️ The build process completes successfully:
</summary>
```sh
❯ yarn build
yarn run v1.22.19
$ npm run typechain && tsc --project tsconfig.build.json
> @keep-network/tbtc-v2.ts@2.2.0-dev typechain
> rm -rf ./typechain && for i in $npm_package_config_contracts; do typechain --target ethers-v5 --out-dir ./typechain $i; done && rm ./typechain/index.ts
Successfully generated 5 typings!
Successfully generated 9 typings!
✨  Done in 4.10s.
```
</details>
<details><summary>
🧪 Test …

Tinysecp replacement

---

typescript/package.json

We released version 2.2.0, so need to start a next one for development.

TypeScript: Start version 2.3.0-dev

---

typescript/test/lib/electrum.test.ts

#Refs: https://github.com/keep-network/tbtc-v2/issues/714.
This PR adds a missing unit test for `Electrum.getTransaction`.

Increase unit test coverage: unit tests for Electrum.getTransaction

---

typescript/api-reference/classes/DepositsService.md
typescript/src/services/deposits/deposits-service.ts
typescript/test/services/deposits.test.ts

#Refs: https://github.com/keep-network/tbtc-v2/issues/714.
This PR adds missing unit tests for `DepositService.initDeposit`.

Increase unit test coverage: unit tests for DepositService.initiateDeposit

---

typescript/package.json

We released version 2.3.0, so need to start a next one for development.

TypeScript: Start version 2.4.0-dev

---

.github/workflows/monitoring.yml
monitoring/docs/monitoring-and-telemetry.adoc
monitoring/package.json
monitoring/src/block-explorer.ts
monitoring/yarn.lock

Refs: https://github.com/threshold-network/solidity-contracts/issues/150
Here we adjust the tBTC v2 monitoring tool to the new Sepolia testnet.

Add support for Sepolia testnet in monitoring

---

monitoring/docs/monitoring-and-telemetry.adoc

Here we fix the depth of the `Stale redemption` section header.

Fix typo in the monitoring and telemetry document

---

solidity/contracts/bridge/WalletProposalValidator.sol
solidity/test/bridge/WalletProposalValidator.test.ts

#Refs: https://github.com/keep-network/keep-core/issues/3733.
This PR adds moving funds proposal validation to the wallet proposal validator smart contract.
The validation performs several checks:
- the source wallet's state must be MovingFunds,
- the source wallet's commitment hash must be submitted,
- the target wallets from the proposal must match the submitted commitment hash,
- the proposed fee must be greater than zero,
- the transaction proposed fee must not exceed the maximum fee.

Added validation of moving funds proposal

---

solidity/contracts/bridge/WalletProposalValidator.sol
solidity/test/bridge/WalletProposalValidator.test.ts

Refs: https://github.com/keep-network/keep-core/issues/3733
This PR is a follow-up to https://github.com/keep-network/tbtc-v2/pull/757.
The following checks were added:
- source wallet must be positive,
- source wallet BTC balance must be equal to or greater than the `movingFundsDustThreshold` parameter.

Added source wallet BTC balance check

---

solidity/contracts/bridge/WalletProposalValidator.sol
solidity/test/bridge/WalletProposalValidator.test.ts

#Refs: https://github.com/keep-network/keep-core/issues/3733.
#Depends on: https://github.com/keep-network/tbtc-v2/pull/757.
This PR adds moved funds sweep proposal validation to the wallet proposal validator smart contract.

Added validation of moved funds sweep proposal

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/Deposit.sol
solidity/contracts/bridge/WalletProposalValidator.sol
solidity/test/bridge/Bridge.Deposit.test.ts
solidity/test/bridge/WalletProposalValidator.test.ts
solidity/test/vault/TBTCVault.OptimisticMinting.test.ts

Refs: https://github.com/keep-network/tbtc-v2/issues/749
Here we expose the `revealDepositWithExtraData` function in the `Bridge` contract. This function allows revealing a deposit whose funding transaction embeds arbitrary 32-byte extra data. 
The new function opens a variety of use cases. An EOA depositor can craft a Bitcoin deposit transaction that allows a third-party smart contract to manage the deposit and provide additional services on top. In this case, 32-byte extra data can be used to securely attribute the deposit to the original EOA depositor.  
The `revealDepositWithExtraData` was added next to the existing `revealDeposit` function to provide backward compatibility of the `Bridge` contract API. The `Deposit` library that does the heavy lifting was refactored to handle both …

Expose `revealDepositWithExtraData` in the `Bridge` contract

---

typescript/api-reference/README.md
typescript/api-reference/classes/ElectrumClient.md
typescript/api-reference/classes/EthereumBridge.md
typescript/api-reference/interfaces/BitcoinClient.md
typescript/api-reference/interfaces/BitcoinSpvProof.md
typescript/api-reference/interfaces/BitcoinTxMerkleBranch.md
typescript/src/lib/bitcoin/client.ts
typescript/src/lib/bitcoin/spv.ts
typescript/src/lib/electrum/client.ts
typescript/src/lib/ethereum/bridge.ts
typescript/test/data/deposit-sweep.ts
typescript/test/data/proof.ts
typescript/test/data/redemption.ts
typescript/test/lib/bitcoin.test.ts
typescript/test/lib/electrum.test.ts
typescript/test/lib/ethereum.test.ts
typescript/test/services/maintenance.test.ts
typescript/test/utils/mock-bitcoin-client.ts
typescript/yarn.lock

Refs: https://github.com/keep-network/tbtc-v2/security/advisories/GHSA-wg2x-rv86-mmpx
The SPV proof verifier used by the `Bridge` contract has been changed. It now expects the coinbase's preimage and merkle proof to be submitted as part of the proven transaction's SPV proof. Here we adhere to this requirement by adjusting the SDK's SPV proof builder accordingly.
Note: Core changes presented in this PR are equivalent to https://github.com/keep-network/keep-core/pull/3762

SDK: Add coinbase data to the SPV proof builder

---

typescript/api-reference/README.md
typescript/api-reference/classes/Deposit.md
typescript/api-reference/classes/DepositScript.md
typescript/api-reference/classes/DepositsService.md
typescript/api-reference/classes/EthereumBridge.md
typescript/api-reference/classes/EthereumDepositorProxy.md
typescript/api-reference/enums/WalletState-1.md
typescript/api-reference/interfaces/DepositReceipt.md
typescript/api-reference/interfaces/DepositRequest.md
typescript/api-reference/interfaces/DepositorProxy.md
typescript/api-reference/interfaces/RedemptionRequest.md
typescript/api-reference/interfaces/Wallet.md
typescript/api-reference/modules/WalletState.md
typescript/src/lib/contracts/bridge.ts
typescript/src/lib/contracts/depositor-proxy.ts
typescript/src/lib/contracts/index.ts
typescript/src/lib/ethereum/bridge.ts
typescript/src/lib/ethereum/depositor-proxy.ts
typescript/src/lib/ethereum/index.ts
typescript/src/services/deposits/deposit.ts
typescript/src/services/deposits/deposits-service.ts
typescript/test/lib/ethereum.test.ts
typescript/test/services/deposits.test.ts
typescript/test/utils/mock-depositor-proxy.ts

Refs: https://github.com/keep-network/tbtc-v2/issues/749
Pull request https://github.com/keep-network/tbtc-v2/pull/760 introduced a possibility to embed 32-byte extra data within the deposit script. This simple change opens multiple possibilities. Notably, third-party smart contracts can now act as depositor proxies and reveal deposits on depositors' behalf. This way, proxy contracts receive minted TBTC and can provide extra services without requiring additional actions from the depositor (e.g., deposit it to a yield protocol or bridge it to an L2 chain). This, in turn, empowers third-party protocols to use tBTC as a foundation and propose additional value on top of it. The goal of this pull request is to facilitate the integration of such third-party protocols through tBTC SDK.
First of …

SDK: Support for depositor proxies

---

solidity/.nvmrc
solidity/contracts/integrator/TBTCDepositorProxy.sol
solidity/contracts/test/TestTBTCDepositorProxy.sol
solidity/test/integrator/TBTCDepositorProxy.test.ts

In this PR I propose some modifications to the initial implementation of `AbstractTBTCDepositor` contract (https://github.com/keep-network/tbtc-v2/pull/778).
Integrators may be interested in adding more fees to the deposit amount. For this reason, it may be cleanest to calculate it based on the initial deposit amount. By returning the value here they will avoid the need to read the funding deposit amount from the storage again.
I added modifications to the MockBridge and MockTBTCVault contracts, that were useful in tests of the integrator's implementation (https://github.com/thesis/acre/pull/91).

Tweaks to `AbstractTBTCDepositor` contract

---

solidity/package.json

Here we remove the rule we added to exclude test contracts from published NPM package. In
https://github.com/keep-network/tbtc-v2/pull/779 we prepared a `TestTBTCDepositor` contract to be used by the integrators in tests for mocking the tBTC Bridge contracts. It is useful to include this file in the package, so the integrators can leverage it.

Include test contracts in published NPM package

---

solidity/contracts/integrator/AbstractTBTCDepositor.sol
solidity/test/integrator/AbstractTBTCDepositor.test.ts

To optimize gas usage we removed `pendingDeposits` mapping. This operation reduces gas usage of `_initializeDeposit` function by ~20k gas.
After this change it is implementation's contract responsibility to ensure `_finalizeDeposit` function cannot be called twice for the same deposit.
`_initializeDeposit` function is not affected as the bridge blocks possibility of revealing the same deposit twice.

Don't track pending deposits in AbstractTBTCDepositor contract

---

solidity/contracts/integrator/AbstractTBTCDepositor.sol
solidity/contracts/test/TestTBTCDepositor.sol

This allows projects using `MockTBTCVault` for tests of `AbstractTBTCDepositor`-based contracts to inject custom logic, such as minting of tBTC token. This logic is not important for tests of `AbstractTBTCDepositor` but is usually important for tests of derived contracts.

Marked MockTBTCVault functions virtual

---

solidity/contracts/integrator/AbstractTBTCDepositor.sol
solidity/test/integrator/AbstractTBTCDepositor.test.ts

In all cases considered so far, the child contract emits its own events in the functions calling `_initializeDeposit` and `_finalizeDeposit`. The events emitted by child contracts have the advantage of emitting decoded extra data in the parameters. We could emit events from the parent contract as well but they cost gas and we are emitting the same data in child contract events. Also, we sometimes need to be creative in child contracts and come up with other names than `DepositInitialized` and `DepositFinalized` even though that is exactly what happens :)
Also, lesson learned today: if there is a contract inheriting from `AbstractTBTCDepositor` and declaring an event with the same name - say `DepositFinalized` - when testing the contract whether the event was emitted, Hardhat will complain …

Do not emit events from AbstractTBTCDepositor

---

solidity/contracts/integrator/AbstractTBTCDepositor.sol
solidity/contracts/test/TestTBTCDepositor.sol
solidity/test/integrator/AbstractTBTCDepositor.test.ts

In this PR we introduce two changes to the AbstractDepositorContract around the deposit amounts.
Integrators may need a minimum deposit amount to introduce validation if the amount the user wants to deposit meets the Bridge requirement of a deposit to exceed the dust threshold.
Originally proposed in https://github.com/thesis/acre/pull/253#discussion_r1500715013.
The amount may be useful for integrators for validations of the deposit amount. Originally proposed in https://github.com/thesis/acre/pull/253#discussion_r1500680454.
It turns out that this version where we read from the storage:
```solidity
initialDepositAmount =
bridge.deposits(depositKey).amount *
SATOSHI_MULTIPLIER;
```
costs `117 366` gas.
Which is less than an alternative approach:
```solidity
initialDepositAmount = …
```

Expose deposit amounts in AbstractDepositorContract

---

solidity/contracts/bridge/Bridge.sol
solidity/contracts/bridge/BridgeGovernance.sol
solidity/contracts/bridge/BridgeState.sol
solidity/contracts/bridge/Redemption.sol
solidity/contracts/bridge/RedemptionWatchtower.sol
solidity/contracts/bridge/WalletProposalValidator.sol
solidity/deploy/40_deploy_redemption_watchtower.ts
solidity/deploy/41_transfer_redemption_watchtower_ownership.ts
solidity/hardhat.config.ts
solidity/test/bridge/Bridge.Governance.test.ts
solidity/test/bridge/Bridge.Parameters.test.ts
solidity/test/bridge/Bridge.Redemption.test.ts
solidity/test/bridge/RedemptionWatchtower.test.ts
solidity/test/bridge/WalletProposalValidator.test.ts
solidity/test/fixtures/bridge.ts

Closes: https://github.com/keep-network/tbtc-v2/issues/781
Here we present the implementation of the redemptions veto mechanism, specified in the [TIP-072: Optimistic redemptions](https://forum.threshold.network/t/tip-072-optimistic-redemptions/793). 
The current byte size of the `Bridge` contract (~22 kB) is close to the limit. To leave some space for future `Bridge` upgrades, we decided to encapsulate the logic of the redemption veto mechanism in a separate upgradeable contract called `RedemptionWatchtower`, and attach it to the existing `Bridge` instance. Such a design has a positive impact on the `Bridge` size, nicely separates the concerns, and reduces the amount of direct changes in the living `Bridge` instance.
The `RedemptionWatchtower` contract acts as a central point for …

Redemptions veto mechanism

---

.github/workflows/contracts-docs.yml

Previously we've been adding comments to PRs modifying Solidity contracts about available previews of the API documentation. As each push to the PR branch results in one such comment, PRs with a lot of pushes get quite busy with a lot of the similar comments. In the future it would be good to modify our commenting mechanism so that it would just leave one comment per PR and update it on each push. Until we do that we're turning off the PR commenting, to increase readability.
Ref:
https://github.com/keep-network/keep-core/pull/3791
https://github.com/threshold-network/solidity-contracts/pull/165

Don't add comments about API docs previews to PRs

---

solidity/contracts/bridge/WalletProposalValidator.sol
solidity/test/bridge/WalletProposalValidator.test.ts

This PR updates the proposal validation of deposit sweeps and redemptions.
The proposal validation used to fail when wallet state was `MovingFunds`, but `submitDepositSweepProof` and `submitRedemptionProof` allow `MovingFunds` wallets.
Since now  proposals with wallet state `MovingFunds` will pass.

Updated deposit sweep and redemption proposal validation

---

solidity/package.json

We released version 1.6.0, so need to start a next one for development.

Solidity: Start version 1.7.0-dev

---

typescript/api-reference/README.md
typescript/api-reference/classes/ElectrumClient.md
typescript/api-reference/interfaces/ElectrumCredentials.md
typescript/src/lib/ethereum/index.ts

There is no need to fetch `WalletRegistry` address from the `Bridge`. It is already loaded from the artifact. This allows saving a call to the Ethereum RPC server.

Remove redundant wallet registry fetch

---

solidity/contracts/l2/L1BitcoinDepositor.sol
solidity/test/l2/L1BitcoinDepositor.test.ts

If someone front-runs the Relayer Bot to call the `initializeDeposit` function, the Relayer Bot's transaction will be reverted, wasting a substantial amount of gas since the validation of duplicate deposits is performed very late in the process, in the tBTC `Bridge` smart contract. This is cost-effective to the front-runner, as the refund mechanism attempts to make callers slightly net-positive.
To mitigate the above, anyone is allowed to relay deposits but reimbursement only occurs for a closed set of relayers.

Authorized reimbursements in the `L1BitcoinDepositor` contract

---

solidity/contracts/l2/L1BitcoinDepositor.sol
solidity/contracts/l2/L2BitcoinDepositor.sol

Depends on: https://github.com/keep-network/tbtc-v2/pull/804
Here we add the missing zero-address checks to prevent incorrectly set values.

Add zero address checks for `L*BitcoinDepositor` initializers

---

solidity/contracts/l2/L1BitcoinDepositor.sol
solidity/contracts/l2/L2BitcoinDepositor.sol

Depends on: https://github.com/keep-network/tbtc-v2/pull/805
Here we fix the Solidity version to be `0.8.17` which is used across all tBTC contracts.

Lock pragma version for `L*BitcoinDepositor` contracts

---

typescript/package.json

We released version 2.4.0, so need to start a next one for development.

TypeScript: Start version 2.5.0-dev

---

typescript/api-reference/README.md
typescript/api-reference/classes/EthereumBridge.md
typescript/api-reference/interfaces/Wallet.md
typescript/src/lib/contracts/bridge.ts
typescript/src/lib/ethereum/bridge.ts
typescript/src/services/redemptions/redemptions-service.ts

Closes: https://github.com/keep-network/tbtc-v2/issues/812
The current logic used to fetch wallet public keys was throwing errors while used for `Closed` or `Terminated` wallets. This is because the `WalletRegistry` contract does no longer hold the public key for such wallets. In effect, the exception was propagated upstream and caused problems while searching wallets for redemption.
Here we fix that problem by making the public key field optional and keeping it undefined for closed/terminated wallets. That way, the client code can detect this fact and omit closed/terminated wallets during processing.

Improve public key fetching for closed/terminated wallets

---

typescript/api-reference/README.md
typescript/api-reference/classes/EthereumTBTCToken.md
typescript/api-reference/classes/RedemptionsService.md
typescript/api-reference/interfaces/RedeemerProxy.md
typescript/api-reference/interfaces/TBTCToken.md
typescript/src/lib/contracts/tbtc-token.ts
typescript/src/lib/ethereum/tbtc-token.ts
typescript/src/services/redemptions/index.ts
typescript/src/services/redemptions/redeemer-proxy.ts
typescript/src/services/redemptions/redemptions-service.ts
typescript/test/services/redemptions.test.ts
typescript/test/utils/mock-redeemer-proxy.ts
typescript/test/utils/mock-tbtc-token.ts

In this PR we introduce a RedeemerProxy interface that can be used by integrators to route tBTC redemption through the tBTC Bridge.
An example of the integrator is Acre's [BitcoinRedeemer contract](https://github.com/thesis/acre/blob/main/solidity/contracts/BitcoinRedeemer.sol) that requires the redemption data to handle stBTC -> tBTC -> Bitcoin conversion in one transaction.
When redeeming tBTC the challenge is to assemble redemption data to contain valid wallet UTXO and other data in the format expected by the Bridge.
It is expected that the integrator will implement `RedeemerProxy` interface by exposing two functions:
- `redeemerAddress(): ChainIdentifier` - that will return the Ethereum address to which the tBTC balance will be assigned in case of problems with redemption,
- …

Implement redemptions with a proxy for redemption integrations

---

typescript/api-reference/README.md
typescript/api-reference/classes/EthereumBridge.md
typescript/api-reference/enums/WalletState-1.md
typescript/api-reference/interfaces/Bridge.md
typescript/api-reference/interfaces/DepositReceipt.md
typescript/api-reference/interfaces/DepositRequest.md
typescript/api-reference/interfaces/RedemptionRequest.md
typescript/api-reference/interfaces/Wallet.md
typescript/api-reference/modules/WalletState.md
typescript/src/lib/contracts/bridge.ts
typescript/src/lib/ethereum/bridge.ts
typescript/test/utils/mock-bridge.ts

So far, the SDK exposed a way to fetch pending redemptions using plain-text wallet public key. This is problematic for use cases where the client has only the wallet public key hash. As the SDK uses the PKH internally anyway, we can easily address this problem by exposing a public function allowing to fetch pending redemptions using wallet PKH.

SDK: Expose a way to fetch pending redemptions using wallet PKH

---

CONTRIBUTING.adoc

Added rules about good commit messages to the `CONTRIBUTING.md` document. The same rules we have been following so far, so nothing revolutionary. Just to keep the new contributors informed.

Add commit message rules to CONTRIBUTING

---

README.adoc

... unless coding styles require it.

We shouldn't refer to tBTC as "TBTC"

---

solidity/contracts/Timelock.sol
solidity/deploy/42_deploy_timelock.ts
solidity/test/Timelock.test.ts

Upgrade scenario: https://github.com/keep-network/tbtc-v2/issues/830
The goal is to deploy a Timelock between the `Bridge`, `RedemptionWatchtower`, and `WalletRegistry` `ProxyAdmin`s and the Threshold Council multisig to enforce 24h delay between upgrades.
This changeset adds the deployment script and a basic integration test simulation Bridge proxy upgrade. The goal is not to test OpenZeppelin implementation but to prove the integration works and present how the upgrade transaction should be assembled.

Timelock for the Bridge and other critical components

---

CODEOWNERS

Including all original tbtc v2 smart contract developers as code owners.
This change allows to open the repository for more contributors, including DAO developers.

Adding CODEOWNERS for smart contracts

---

.github/workflows/npm-contracts.yml
solidity/README.adoc

Update the GitHub Actions CI configuration to use Node 18.x instead of 14.x.
This change addresses build failures caused by a transitive dependency (secp256k1@4.0.4) requiring Node >=18.0.0. Previously, our CI was running Node 14.x, which was incompatible with the latest dependency updates coming through packages such as ethereum-cryptography and ganache.
No changes to the application code are included; this update only affects the CI configuration.

ci: update Node version to 18.x in GitHub Actions workflow

---

typescript/api-reference/README.md
typescript/api-reference/classes/EthereumExtraDataEncoder.md
typescript/api-reference/classes/EthereumL1BitcoinDepositor.md
typescript/src/lib/ethereum/artifacts/mainnet/SuiBTCDepositorWormhole.json
typescript/src/lib/ethereum/artifacts/sepolia/SuiBTCDepositorWormhole.json
typescript/src/lib/ethereum/l1-bitcoin-depositor.ts
typescript/src/lib/sui/bitcoin-depositor.ts

This commit updates the API documentation for Ethereum-related classes and introduces new deployment artifacts for the SuiBTCDepositorWormhole on both mainnet and Sepolia networks.
- Updated line references in the API documentation for `EthereumExtraDataEncoder` and `EthereumL1BitcoinDepositor` to reflect the latest code changes.
- Added new JSON files for `SuiBTCDepositorWormhole` artifacts, including contract ABI and deployment details for both mainnet and Sepolia.
These updates ensure that the documentation is accurate and that the new SuiBTCDepositorWormhole functionality is properly integrated into the project.

Update Ethereum API references and add SuiBTCDepositorWormhole artifacts

---

typescript/package.json

This change prepares the package for the next development cycle.

chore: bump version to 2.8.0-dev in package.json
