docs/rfc/rfc-1.adoc
The intent of this document is to provide a living source of reference for the design for the tBTCv2 system and be useful both on an descripive level and a technical level.
as of right now, it is but a rough draft :)
tagging @pdyraga for early review - I want to make sure the direction that this is going is correct before I write more!
=> RFC 1: tBTCv2 Design

yearn/contracts/ConvexStrategy.sol, yearn/contracts/CurveVoterProxyStrategy.sol
Depends on: #47 
Added a governance delay for strategies parameters updates.
=> Governance delay for strategies parameters

yearn/contracts/ConvexStrategy.sol, yearn/contracts/CurveVoterProxyStrategy.sol, yearn/contracts/SaddleStrategy.sol
Use `immutable` variables in several places to save some gas.
=> Use `immutable` vars wherever possible

.github/workflows/contracts.yml, .github/workflows/yearn.yml
The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.
=> Adding cron for daily tests and builds on Mercode

docs/rfc/rfc-1.adoc
This PR attempts to formalize some of the conversations we've had around how to pick the initial parameters for group selection.
Tagging @pdyraga and @eth-r for review
=> Groupsize Seeding

docs/rfc/rfc-1.adoc
This PR adds a blurb that talks about our strategy for when we submit a transaction with too low of a bitcoin fee. Tagging @pdyraga and @michalinacienciala for review
follows up on the comments from https://github.com/keep-network/tbtc-v2/pull/62#discussion_r749074475
=> RFC 1: Incrementing Fee

docs/rfc/rfc-1.adoc
Quick & Simple PR: I noticed some miscellaneous pieces that were individually wrong but weren't big enough to create cards for, so they got lumped together to create a PR.
tagging @michalinacienciala for review
=> RFC 1: Miscellaneous Cleanup

docs/rfc/rfc-1.adoc
Since we're the process of increasing the fees plays with both timing and pricing logic, this PR points out some of the pitfalls in the hopes that they're carefully avoided.
=> RFC 1: Bin Packing Eligibility With Respect To Increasing Fees

docs/rfc/rfc-1.adoc
Simple formatting PR - we take all of the existing governable parameters and collect them into an index.
tagging @michalinacienciala for review (feel free to merge if it looks fine to you).
=> RFC 1: Governable Parameter Index!

solidity/contracts/bank/Bank.sol, solidity/package.json, solidity/test/bank/Bank.test.ts, solidity/yarn.lock
Refs https://github.com/keep-network/tbtc-v2/issues/40
`Bank` contract is a central component tracking Bitcoin balances. Balances can be transferred between holders and holders can approve their balances to be spent by others. Balances in the Bank are updated for depositors who deposit their Bitcoin into the Bridge and only the Bridge can increase balances.
`Bank` contract is a governable contract and the Governance can upgrade the Bridge address.
=> The Bitcoin Bank

docs/rfc/rfc-1.adoc
This PR specs out the rough draft for a mechanism to allow depositors to pay to have their deposits immediately swept.
=> RFC 1: Skip the Sweeping Line

.github/workflows/tbtc-ts.yml, tbtc-ts/README.adoc
Refs: #79 
Here we add a workflow for `tbtc-ts` library consisting of `detect-changes`, `build-and-test` and `format` jobs. Updated the `README.adoc` by the way to test the workflow in action.
=> CI workflow for `tbtc-ts`

docs/rfc/rfc-1.adoc
refs #34 
This PR further expands on the heartbeat design, especially around the interaction between unstaking and heartbeats.
=> RFC 1: More Heartbeat Design

typescript/package.json, typescript/src/electrum.ts, typescript/test/data/electrum.ts, typescript/test/electrum.test.ts, typescript/yarn.lock
Closes: #122 
This pull request introduces an implementation of the Bitcoin client, based on the Electrum server.
=> Electrum-based implementation of the Bitcoin client

solidity/contracts/bridge/Bridge.sol, solidity/contracts/bridge/BridgeState.sol, solidity/test/bridge/Bridge.Frauds.test.ts, solidity/test/fixtures/index.ts
Refs #https://github.com/keep-network/tbtc-v2/issues/152
This PR adds functionalities for updating parameters related to frauds in `Bridge`.
=> Updating fraud related parameters

solidity/contracts/bridge/Bridge.sol, solidity/contracts/bridge/BridgeState.sol, solidity/test/bridge/Bridge.test.ts, solidity/test/fixtures/index.ts
Refs #https://github.com/keep-network/tbtc-v2/issues/152
This PR adds functionalities for updating parameters related to deposits in Bridge.
=> Updating deposit related parameters

solidity/contracts/bridge/Bridge.sol, solidity/contracts/bridge/BridgeState.sol, solidity/test/bridge/Bridge.test.ts, solidity/test/fixtures/index.ts
Refs #https://github.com/keep-network/tbtc-v2/issues/152
This PR adds functionalities for updating parameters related to redemptions in Bridge.
=> Updating redemption related parameters

solidity/contracts/bridge/Bridge.sol, solidity/contracts/bridge/BridgeState.sol, solidity/test/bridge/Bridge.MovingFunds.test.ts, solidity/test/fixtures/index.ts
Refs #https://github.com/keep-network/tbtc-v2/issues/152
This PR adds functionalities for updating parameters related to moving funds in Bridge.
=> Updating moving funds parameters

.github/workflows/contracts.yml, solidity/deploy/05_deploy_bridge.ts, solidity/package.json, solidity/yarn.lock
Deployment dry-run was not being executed for PRs. With this PR we want to fix it.
=> Fix deployments dry-run execution in CI

solidity/contracts/bridge/BridgeState.sol
It's a follow-up for https://github.com/keep-network/tbtc-v2/pull/242#discussion_r870255377
=> Minor typo fix

docs/rfc/rfc-1.adoc, docs/rfc/rfc-2.adoc, solidity/contracts/bridge/Redemption.sol, solidity/contracts/bridge/VendingMachine.sol
This PR fixes typoes found in tbtc-v2 repository.
=> Fixed typoes

README.adoc
This PR introduces the mechanism section with an article about wallet creation. Most of the heavy lifting was done in the *very* involved dedicated sections: https://github.com/keep-network/keep-core/tree/main/solidity/ecdsa#the-mechanism and https://github.com/keep-network/keep-core/tree/main/solidity/random-beacon#the-mechanism so rather than repeat and risk getting desynced, we link to it.
On top, we talk about the tbtc v2 specific implementation (how we're interfacing with the wallet registry code).
Tagging @pdyraga and @lukasz-zimnoch for review
=> Wallet Creation Mechanism Readme

README.adoc
This PR fills in the wallet closure docs! @pdyraga can you take a look and let me know if this is the level of depth that you're looking for?
Also, the param numbers are completely off-the-cuff
=> Wallet Closure

docs/index.adoc
This one is a little shorter - @pdyraga anything else you think is relevant here? I was thinking about allowance stuff, but felt like that wasn't part of the mechanism, and was better suited for talking about the bank and vault in general
=> Mechanism Writeup: Unminting

docs/index.adoc
This PR adds a section about the Bridge <> Bank <> Vault design, discusses why we chose to separate concerns like that, and discusses each piece in detail.
=> Architecture Writeup: Bridge, Bank, Vault

docs/index.adoc
Refs #144 
Described the concept of a maintainer and how it is implemented in
`MaintainerProxy`.
=> TBTC documentation: Maintainers

docs/index.adoc
Refs #144 
[Added an overview of depositing and redeeming](https://github.com/keep-network/tbtc-v2/commit/d80d7bd55ade0abdcc4ff3067dc38c5c097bae91) so that everyone can get an overview of how the system works without a deep-dive into The Mechanism. [Moved Upgradeability and Wallet States to the end of architecture section](https://github.com/keep-network/tbtc-v2/commit/87332b35f7330134cfaad83b14abb36f6f4b9d60). It makes sense to discuss Bridge, Bank, and Vault first and have the reader understand these concepts before anything else.
=> TBTC documentation: deposit and redemption overview plus small reorg

docs/index.adoc
This PR adds @michalinacienciala 's wonderful diagrams to the index doc.
I'm still really unsure about where to fit them because they're such show-stealers that trying to weave them into an explanation is unwieldy.
I ended up giving them their own section, but if @pdyraga or @michalinacienciala have better ideas, I'm game!
=> TBTC Documentation: Diagrams!

solidity/test/integration/FullFlow.test.ts, solidity/test/integration/data/integration.ts, solidity/test/integration/utils/fixture.ts
Closes: #250 
This PR adds a full deposit-redemption flow integration test.
The flow is as follows:
1) wallet creation
2) revealDeposit
3) submitDepositSweepProof
4) requestRedemption
5) submitRedemptionProof
After each step checks were performed.
The test data comes from transactions that were made in Bitcoin testnet.
=> Integration test: full flow

solidity/test/bridge/Bridge.Deposit.test.ts, solidity/test/bridge/Bridge.MovingFunds.test.ts, solidity/test/bridge/Bridge.Redemption.test.ts
This PR adds unit tests to check that the SPV proof validating functions in the Bridge require transaction data that is longer than 64 bytes.
The tests verify that for all Bridge transactions that involve validating SPV proof the transaction data (`version`, `locktime`, `inputs`, `outputs`) length must always be greater than 64 bytes from the point of view of the Bridge.
* For `submitDepositSweepProof`, `submitMovingFundsProof`, `submitMovedFundsSweepProof`
We first validate that there is at least one input and one output and we check formatting of inputs and outputs (this happens in `validateVin` and `validateVout` functions).
Additionally, when processing the output we ensure that it contains an output script that is at least 23-bytes long (function `extractPubKeyHash`).
* For …
=> Unit tests checking the minimum transaction length for SPV proof transactions

solidity/deploy/00_resolve_relay.ts, solidity/deploy/05_deploy_bridge.ts
This PR updates the bitcoin relay deployment scripts, so that they use the `LightRelay` contract.
=> Updated relay deployment script

solidity/test/bridge/VendingMachine.Upgrade.test.ts
Unit tests cover the scenario based on Agoristen's proposal from https://forum.threshold.network/t/tip-027b-tbtc-v1-the-sunsettening/357/20
In this scenario, Redeemer mints TBTC v2 with their own BTC. Then, they unwrap back to TBTC v1 and redeem BTC from the v1 system.
**Step 1 - TBTC v1 transfer, TBTC v2 ownership transfer**
TBTC v1 is transferred from `VendingMachine` to `TBTCVault` along with TBTC v2 token ownership.
**Step 2 - TBTC v1 transfer back**
TBTC v1 is transferred back to `VendingMachine` from the `TBTCVault`.
**Step 3 - BTC deposits**
The v2 depositor (v1 redeemer) deposits BTC to the v2 system to mint TBTC v2.
**Step 4 - TBTC v1 redemption**
The v2 depositor (v1 redeemer) unwraps TBTC v1 from TBTC v2 via
=> Unit tests covering Agoristen's proposal for v1 sunsetting

typescript/package.json
We start a new version as v1.0.0 was already published.
=> Start typescript v1.1.0-dev

typescript/src/bitcoin-network.ts, typescript/src/electrum.ts
We need to retry requests to Electrum endpoints as some of them are failing due to server errors.
Depends on: https://github.com/keep-network/tbtc-v2/pull/516
Closes: https://github.com/keep-network/tbtc-v2/issues/499
Closes: https://github.com/keep-network/tbtc-v2/issues/485
=> Retries for Electrum requests

monitoring/README.adoc, monitoring/docs/monitoring-and-telemetry.adoc
Closes: https://github.com/keep-network/pm/issues/33
Here we add a document describing the entire monitoring and telemetry system.
=> Monitoring and telemetry document

monitoring/docs/monitoring-and-telemetry.adoc, monitoring/src/wallet-monitor.ts, monitoring/yarn.lock
Closes: https://github.com/keep-network/tbtc-v2/issues/551
Depends on: https://github.com/keep-network/tbtc-v2/pull/563
Here we enhance the wallet monitor with DKG lifecycle events. The new events are:
An **informational system event** indicating that a new DKG result was submitted to the on-chain WalletRegistry contract. This event is directly sent to Discord as a notification that does not require any action.
An **informational system event** indicating that the submitted DKG result was approved on the on-chain WalletRegistry contract. This event is directly sent to Discord as a notification that does not require any action.
A **critical system event** indicating that the submitted DKG result was challenged on the on-chain WalletRegistry contract. This event is sent to Sentry hub and …
=> Monitor DKG lifecycle

typescript/package.json
Version 1.1.0 was already released.
=> Typescript: Start version 1.2.0-dev

docs/README.adoc
=> Fix: typos

.github/workflows/cross-chain-polygon.yml, cross-chain/arbitrum/deploy_l2/13_update_with_optimism_in_wormhole_gateway_mapping.ts, cross-chain/arbitrum/deploy_l2/14_update_with_polygon_in_wormhole_gateway_mapping.ts, cross-chain/optimism/deploy_l2/14_update_with_polygon_in_wormhole_gateway_mapping.ts, cross-chain/polygon/tsconfig.json
This PR:
- Changes "governance" signer to "deployer" for local development purposes in the deployment scripts when updating wormhole gateway mappings. It will fix the tests run by CI.
- Adding CI workflow for Polygon module.
=> Cross chain touchups

solidity/deploy/39_authorize_light_relay_maintainer_proxy_in_light_relay.ts, system-tests/package.json, system-tests/test/utils/bitcoin.ts, typescript/src/electrum.ts
There were a couple of reasons why the system tests were broken.
1. The current setup does not include `authorize` function for Goerli or `system_tests` network. When running system tests the `39_authorize_light_relay_maintainer_proxy_in_light_relay.ts` deployment script failed because it couldn't find the `authorize` function. This `authorize` function is unnecessary for system tests and we can skip it.
2. Seems that a bitcoin client needs a bit of time to catch up with the bitcoin chain before making a call. When waiting for a transaction confirmation the "wait" code was moved to the beginning of the function instead of having it at the end. This way a bitcoin client will have some time to "synch" and this change only affects the system-tests, and not the `tbtc-v2.ts` lib which is used …
=> Fixing system tests

solidity/.openzeppelin/mainnet.json, solidity/deploy/81_upgrade_wallet_coordinator_v2.ts, solidity/deployments/mainnet/WalletCoordinator.json, solidity/export.json
Refs: https://github.com/keep-network/tbtc-v2/issues/641
This PR contains updates to the deployment script and artifacts of the WalletCoordinator contract deployed to mainnet.
=> Deployment artifacts for WalletCoordinator upgrade

typescript/src/services/deposits/deposits-service.ts, typescript/src/services/redemptions/redemptions-service.ts
#Refs: https://github.com/keep-network/tbtc-v2/issues/715.
This PR adds additional validation of Bitcoin addresses for recovery and redemption.
=> Harden Bitcoin address validation

solidity/contracts/integrator/AbstractTBTCDepositor.sol
Emphasize the importance of finalization tracking.
Follow-up from: https://github.com/keep-network/tbtc-v2/pull/783#discussion_r1482977049
=> Capslock dev doc for AbstractTBTCDepositor#_finalizeDeposit

typescript/src/lib/ethereum/artifacts/mainnet/Bridge.json, typescript/src/lib/ethereum/artifacts/mainnet/WalletRegistry.json, typescript/src/lib/ethereum/artifacts/sepolia/Bridge.json
Some smart contract upgrades landed recently. Here we update contract artifacts in the SDK to reflect that.
=> Update contract artifacts in the SDK

cross-chain/starknet/package.json, cross-chain/starknet/scripts/check_ownership.ts, cross-chain/starknet/scripts/transfer_ownership.ts, typescript/package.json
Typescript project and Starknet's cross-chain deployment version bump.
Introduced check_ownership.ts to verify the ownership status of the StarkNetBitcoinDepositor contract, providing feedback on whether ownership transfer to governance is needed.
Added transfer_ownership.ts to facilitate the transfer of contract ownership from the deployer to governance, including checks to ensure the transfer is valid and logging transaction details.
These scripts enhance the management of contract ownership within the StarkNet integration.
=> feat: add ownership check and transfer scripts for StarkNetBitcoinDepositor & version bump

cross-chain/bob/contracts/Timelock.sol, cross-chain/bob/deploy_l2/03_deploy_timelock.ts, cross-chain/bob/hardhat.config.ts
feat: add timelock controller contract and deployment script on bob
=> feat: add timelock controller on bob
